"""Term Sheet Generator — produces a professional combined proposal DOCX.

Modelled on the Alpha_Ed71_Combined_Proposal.docx benchmark document:
  Part 1 (pages 1-5): Strategic partnership proposal narrative
  Part 2 (pages 6-7): Deal terms and financial tables

~70% of the document is boilerplate matching the UAE benchmark.
~30% is country/state-specific content generated by the LLM.

Includes a HITL gate for term sheet assumptions (deal terms)
that the user can review/adjust before the term sheet is generated.
Changes to key financial terms trigger financial model recalculation.
"""

from __future__ import annotations

import logging
import os
import unicodedata
from datetime import datetime

from pydantic import BaseModel, Field

from docx import Document as DocxDocument
from docx.shared import Pt as DocxPt, RGBColor as DocxRGB, Cm
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

from models.schemas import (
    CountryProfile, EducationAnalysis, Strategy,
    FinancialModel, FinancialAssumptions, FinancialAssumption, TargetType,
)
from services.llm import call_llm
from config import OUTPUT_DIR

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Term Sheet Assumptions Generator (unchanged — supports HITL gates)
# ---------------------------------------------------------------------------

# Keys that overlap with the financial model and require recalculation
FINANCIAL_MODEL_OVERLAP_KEYS = {
    "ts_upfront_ip_fee",
    "ts_upfront_alphacore_license",
    "ts_upfront_app_content_rd",
    "ts_upfront_lifeskills_rd",
    "ts_upfront_mgmt_fee",
    "ts_upfront_timeback_fee",
    "ts_management_fee_pct",
    "ts_timeback_license_pct",
    "ts_students_year5",
    "ts_per_student_budget",
    "ts_capex_per_school",
}

# Mapping from term sheet assumption keys to financial model assumption keys
TS_TO_FM_KEY_MAP = {
    "ts_upfront_ip_fee": "upfront_ip_fee",
    "ts_upfront_alphacore_license": "upfront_alphacore_license",
    "ts_upfront_app_content_rd": "upfront_app_content_rd",
    "ts_upfront_lifeskills_rd": "upfront_lifeskills_rd",
    "ts_upfront_mgmt_fee": "upfront_mgmt_fee",
    "ts_upfront_timeback_fee": "upfront_timeback_fee",
    "ts_management_fee_pct": "management_fee_pct",
    "ts_timeback_license_pct": "timeback_license_pct",
    "ts_students_year5": "students_year5",
    "ts_per_student_budget": "per_student_budget",
    "ts_capex_per_school": "capex_per_school",
}


def generate_term_sheet_assumptions(
    target: str,
    country_profile: CountryProfile,
    strategy: Strategy,
    financial_model: FinancialModel,
    financial_assumptions: FinancialAssumptions,
) -> FinancialAssumptions:
    """Generate configurable term sheet assumptions for HITL review.

    These are the deal-specific terms that will appear in the term sheet.
    Some overlap with the financial model — if user changes those, a
    recalculation of the financial model is required.
    """
    logger.info("Generating term sheet assumptions for %s", target)

    # Pull current values from financial model/assumptions
    fa = {
        item.key: item.value
        for item in financial_assumptions.assumptions
    }

    mgmt_pct = round(financial_model.management_fee_pct * 100)
    timeback_pct = round(financial_model.timeback_license_pct * 100)
    upfront_ip = financial_model.upfront_ip_fee
    upfront_ip_m = (
        round(upfront_ip / 1_000_000) if upfront_ip > 1_000_000
        else upfront_ip
    )

    # Student targets from financial model
    y5_students = 0
    if financial_model.pnl_projection:
        y5_students = financial_model.pnl_projection[-1].students

    _y5_revenue = 0  # noqa: F841
    if financial_model.pnl_projection:
        _y5_revenue = financial_model.pnl_projection[-1].revenue  # noqa: F841

    per_student = fa.get(
        "per_student_budget",
        fa.get("national_per_student_budget",
               fa.get("mid_tuition", 25_000)),
    )
    capex_per_school = fa.get("capex_per_school", 5_000_000)

    # Backstop based on UAE formula: 50% capacity x tuition x schools x 5yr
    pnl = financial_model.pnl_projection
    num_schools = pnl[-1].schools if pnl else 10
    backstop_annual = round(
        0.5 * y5_students * per_student / 1_000_000
    )
    mgmt_fee_prepay_m = round(
        min(5000, y5_students)
        * per_student * (mgmt_pct / 100) * 2 / 1_000_000
    )

    is_us_state = country_profile.target.type == TargetType.US_STATE

    # --- Upfront value helpers ---
    def _to_m(val: float) -> int:
        """Convert value to $M if over $1M threshold."""
        return (
            round(val / 1_000_000) if val > 1_000_000
            else round(val)
        )

    def _to_m_floor1(val: float) -> int:
        """Convert to $M with a floor of 1."""
        return (
            round(val / 1_000_000) if val > 1_000_000
            else max(1, round(val))
        )

    alpha_desc = (
        "Alpha's equity stake in the JV. "
        "0% = Operator & Licensor model (UAE structure). "
        "100% for direct."
    )

    assumptions = [
        # --- Deal Structure ---
        FinancialAssumption(
            key="ts_partnership_type",
            label="Partnership Structure",
            value=1,  # 1=JV, 2=Licensing, 3=Direct
            min_val=1, max_val=3, step=1,
            unit="type", category="deal",
            description=(
                "1 = Joint Venture, 2 = Licensing, "
                "3 = Direct Operation"
            ),
        ),
        FinancialAssumption(
            key="ts_alpha_ownership_pct",
            label="Alpha Ownership / Control (%)",
            value=0 if not is_us_state else 100,
            min_val=0, max_val=100, step=1,
            unit="%", category="deal",
            description=alpha_desc,
        ),
        FinancialAssumption(
            key="ts_term_years",
            label="Partnership Term (years)",
            value=25, min_val=10, max_val=50, step=5,
            unit="years", category="deal",
            description="Initial partnership duration (renewable)",
        ),
        FinancialAssumption(
            key="ts_exclusivity_years",
            label="Exclusivity Period (years)",
            value=25, min_val=5, max_val=50, step=5,
            unit="years", category="deal",
            description=(
                "Alpha has exclusive rights to the "
                "Alpha model in the territory"
            ),
        ),

        # --- Upfront Payment Breakdown ---
        FinancialAssumption(
            key="ts_upfront_alphacore_license",
            label="AlphaCore License ($M)",
            value=_to_m(financial_model.upfront_alphacore_license),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description=(
                "AlphaCore curriculum OS and learning "
                "management system license"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_app_content_rd",
            label="Customized Country-Specific App Content R&D ($M)",
            value=_to_m(financial_model.upfront_app_content_rd),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description=(
                "R&D for country-specific EdTech app "
                "content and localization"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_lifeskills_rd",
            label="Country-Specific Programs and Life Skills ($M)",
            value=_to_m(financial_model.upfront_lifeskills_rd),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description=(
                "R&D for country-specific life skills "
                "curriculum (AsasCore equivalent)"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_incept_edllm",
            label="Country-Specific Incept EdLLM ($M)",
            value=_to_m(financial_model.upfront_incept_edllm),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description=(
                "Country/State specific Incept EdLLM "
                "development, paid upfront"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_mgmt_fee",
            label="Prepaid Operating Fee ($M)",
            value=_to_m_floor1(financial_model.upfront_mgmt_fee),
            min_val=1, max_val=500, step=5,
            unit="$M", category="fees",
            description=(
                "Target Students Y5 x Per-Student Budget x 10%"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_timeback_fee",
            label="Upfront Timeback Fee ($M)",
            value=_to_m_floor1(financial_model.upfront_timeback_fee),
            min_val=1, max_val=1000, step=5,
            unit="$M", category="fees",
            description=(
                "Target Students Y5 x Per-Student Budget x 20%"
            ),
        ),
        FinancialAssumption(
            key="ts_upfront_ip_fee",
            label="Total Upfront Ask ($M)",
            value=upfront_ip_m,
            min_val=5, max_val=2000, step=5,
            unit="$M", category="fees",
            description=(
                "Sum of all upfront components. "
                "Changes recalculate financial model."
            ),
        ),
        FinancialAssumption(
            key="ts_management_fee_pct",
            label="Management Fee (% of school revenue)",
            value=mgmt_pct,
            min_val=5, max_val=20, step=1,
            unit="%", category="fees",
            description=(
                "Alpha's ongoing management fee. "
                "10% floor is non-negotiable."
            ),
            locked=True,
        ),
        FinancialAssumption(
            key="ts_timeback_license_pct",
            label="Timeback License (% of per-student budget)",
            value=timeback_pct,
            min_val=10, max_val=30, step=1,
            unit="%", category="fees",
            description=(
                "Alpha's technology/IP licensing fee. "
                "20% floor is non-negotiable."
            ),
            locked=True,
        ),
        FinancialAssumption(
            key="ts_mgmt_fee_prepay_years",
            label="Management Fee Prepayment (years)",
            value=2, min_val=0, max_val=5, step=1,
            unit="years", category="fees",
            description="Years of management fee prepaid at signing",
        ),
        FinancialAssumption(
            key="ts_mgmt_fee_prepay_amount",
            label="Management Fee Prepayment Amount ($M)",
            value=max(1, mgmt_fee_prepay_m),
            min_val=0, max_val=500, step=5,
            unit="$M", category="fees",
            description=(
                "Calculated: first-year students x "
                "per-student budget x mgmt fee % x prepay years"
            ),
        ),

        # --- School Portfolio ---
        FinancialAssumption(
            key="ts_students_year5",
            label="Year 5 Student Target",
            value=y5_students,
            min_val=1000, max_val=500_000, step=5000,
            unit="students", category="school_portfolio",
            description=(
                "Target enrollment at scale. "
                "Changes recalculate financial model."
            ),
        ),
        FinancialAssumption(
            key="ts_per_student_budget",
            label="Per-Student Annual Tuition / Budget ($)",
            value=round(per_student),
            min_val=5_000, max_val=100_000, step=500,
            unit="$", category="school_portfolio",
            description=(
                "Blended annual tuition per student. "
                "Changes recalculate financial model."
            ),
        ),
        FinancialAssumption(
            key="ts_num_flagship_schools",
            label="Alpha Flagship Schools",
            value=(
                financial_model.flagship_optimization.total_schools
                if (financial_model.flagship_optimization
                    and financial_model.flagship_optimization.total_schools > 0)
                else int(fa.get("flagship_schools", 3))
            ),
            min_val=0, max_val=10, step=1,
            unit="schools", category="school_portfolio",
            description=(
                "From revenue-maximizing grid search on "
                "metro-level AGI data"
            ),
        ),
        FinancialAssumption(
            key="ts_flagship_tuition",
            label="Flagship School Tuition ($)",
            value=(
                financial_model.flagship_tuition
                if financial_model.flagship_tuition > 0
                else (100_000 if not is_us_state else 50_000)
            ),
            min_val=40_000, max_val=100_000, step=5_000,
            unit="$", category="school_portfolio",
            description="Optimized tuition from grid search",
        ),
        FinancialAssumption(
            key="ts_num_schools",
            label="Total Schools at Scale",
            value=num_schools,
            min_val=1, max_val=500, step=5,
            unit="schools", category="school_portfolio",
            description=(
                "Total number of schools in the network at Year 5"
            ),
        ),

        # --- Counterparty Commitments ---
        FinancialAssumption(
            key="ts_scholarship_backstop_annual",
            label="Scholarship / Tuition Backstop ($M/year)",
            value=max(1, backstop_annual),
            min_val=0, max_val=2000, step=10,
            unit="$M", category="commitments",
            description=(
                "Annual backstop: 50% capacity x tuition "
                "(per UAE formula)"
            ),
        ),
        FinancialAssumption(
            key="ts_backstop_years",
            label="Backstop Commitment Period (years)",
            value=5, min_val=3, max_val=10, step=1,
            unit="years", category="commitments",
            description=(
                "Duration of the scholarship/tuition "
                "backstop commitment"
            ),
        ),
        FinancialAssumption(
            key="ts_launch_capital",
            label="Launch / Marketing Capital ($M)",
            value=50,
            min_val=1, max_val=500, step=5,
            unit="$M", category="commitments",
            description=(
                "Counterparty's commitment to launch "
                "capital and marketing"
            ),
        ),
        FinancialAssumption(
            key="ts_capex_per_school",
            label="CapEx per School Buildout ($M)",
            value=round(capex_per_school / 1_000_000, 1),
            min_val=0.5, max_val=20, step=0.5,
            unit="$M", category="school_portfolio",
            description=(
                "Capital expenditure per new school. "
                "Changes recalculate financial model."
            ),
        ),
    ]

    return FinancialAssumptions(assumptions=assumptions)


def get_financial_model_adjustments(
    term_sheet_adjustments: dict[str, float],
) -> dict[str, float]:
    """Return financial model keys that need recalculation.

    Returns a dict of financial model assumption key -> new value.
    """
    fm_adjustments = {}
    for ts_key, new_val in term_sheet_adjustments.items():
        if ts_key in TS_TO_FM_KEY_MAP:
            fm_key = TS_TO_FM_KEY_MAP[ts_key]
            if ts_key == "ts_capex_per_school":
                new_val = new_val * 1_000_000
            fm_adjustments[fm_key] = new_val
    return fm_adjustments


# ---------------------------------------------------------------------------
# Country-Specific Variables — structured LLM output
# ---------------------------------------------------------------------------

class CountryVariables(BaseModel):
    """Country-specific content for the proposal template.

    ~30% of the proposal document varies by country. This model
    captures all the country-specific text variables needed for
    template substitution.
    """

    country_adjective: str = Field(
        description=(
            "National adjective, e.g. 'French', 'Saudi', 'Brazilian'"
        ),
    )
    jv_program_name: str = Field(
        description=(
            "Name of the country-owned, Alpha-operated school network "
            "(equivalent of 'Ed71' for UAE). "
            "Short, memorable, 2-4 words max. MUST use only plain "
            "ASCII characters (no accents, no diacritics). "
            "MUST NOT contain the word 'Alpha' — these are country-owned "
            "schools and cannot carry the Alpha brand. "
            "MUST be a DIFFERENT name from cultural_program_name. "
            "Good examples: 'Ed71' (UAE), 'Savoir France' (France), "
            "'Vision2030 Learning' (Saudi). "
            "Bad examples: 'Alpha France', 'Alpha Education'."
        ),
    )
    cultural_program_name: str = Field(
        description=(
            "Country's life-skills curriculum program name "
            "(equivalent of 'AsasCore' for UAE). 1-2 words, "
            "culturally resonant. MUST use only plain ASCII "
            "characters (no accents, no diacritics). "
            "MUST be a COMPLETELY DIFFERENT name from jv_program_name — "
            "these are two distinct products: the school network vs. "
            "the life-skills curriculum. "
            "Good examples: 'AsasCore' (UAE), 'VivreCore' (France), "
            "'IqraSkills' (Saudi). "
            "Bad examples: 'Savoir' if jv_program_name is 'Savoir France'."
        ),
    )
    credential_phrase: str = Field(
        description=(
            "Prestige education credential phrase, e.g. "
            "'Educated in the Emirates'. "
            "Format: 'Educated in [Country]'"
        ),
    )
    first_launch_city: str = Field(
        description=(
            "Best city to launch first schools "
            "(capital or major education hub)"
        ),
    )
    second_city: str = Field(
        description="Second city for expansion",
    )
    language_subjects: str = Field(
        description=(
            "Country-specific education app subjects needing "
            "localization (equivalent of 'Arabic, Islamic Studies, "
            "Social Studies, ESL for Arabic speakers'). "
            "Comma-separated list of 4-5 subjects."
        ),
    )
    edu_llm_training: str = Field(
        description=(
            "What the country-specific eduLLM would be trained on "
            "(equivalent of 'UAE language, laws, customs, culture, "
            "and values'). Short phrase."
        ),
    )
    cultural_values: str = Field(
        description=(
            "What the cultural program would encode (equivalent of "
            "'Emirati values, habits, and aspirations'). Short phrase."
        ),
    )
    ministry_reference: str = Field(
        description=(
            "Name of the relevant education authority/ministry"
        ),
    )
    regulatory_framework: str = Field(
        description=(
            "How schools would operate under local law (equivalent "
            "of 'ADEK / Ministry frameworks')"
        ),
    )
    funding_mechanism: str = Field(
        description=(
            "How student funding would work in this country "
            "(1-2 sentences)"
        ),
    )
    national_credential_reference: str = Field(
        description=(
            "A prestige local institution for comparison "
            "(equivalent of 'NYU Abu Dhabi')"
        ),
    )
    country_specific_overview: str = Field(
        description=(
            "2-3 sentences about why this country is ripe for "
            "education transformation. Reference specific national "
            "plans, reforms, or challenges."
        ),
    )
    school_infrastructure_note: str = Field(
        description=(
            "1 sentence about how schools will integrate with "
            "existing infrastructure"
        ),
    )


COUNTRY_VARIABLES_PROMPT = """\
You are preparing a strategic education partnership proposal between
Alpha Holdings, Inc. and {target}. This proposal will be
presented to the head of state and senior government decision-makers.

You need to generate country-specific content variables that will be
inserted into a standardized proposal template (modelled on the UAE
Ed71 deal structure).

Every value must be culturally appropriate, factually accurate, and
diplomatically calibrated for a head-of-state audience. The program
names should sound local, prestigious, and aspirational.

IMPORTANT NAMING RULES:
1. The jv_program_name MUST NOT contain the word "Alpha".
   These are country-owned schools and cannot carry the Alpha brand.
   Use a culturally resonant name instead (e.g. "Ed71", "Savoir France").
2. The jv_program_name and cultural_program_name MUST be COMPLETELY DIFFERENT
   names. They refer to two distinct things:
   - jv_program_name = the country-owned, Alpha-operated SCHOOL NETWORK
     (e.g. "Ed71" for UAE, "Savoir France" for France)
   - cultural_program_name = the country-specific LIFE-SKILLS CURRICULUM
     (e.g. "AsasCore" for UAE, "VivreCore" for France)
   The names must not overlap or be derived from each other.

Country Context:
- Population: {population}
- K-12 Students: {k12_students}
- GDP per capita: ${gdp_per_capita}
- Education ministry: {ministry}
- Head of state: {head_of_state}
- National vision/plan: {national_vision}
- Government type: {government_type}
- Per-student budget for this deal: ${per_student_budget}
- Year 5 student target: {y5_students}

Education Context:
{education_context}

Strategy Context:
{strategy_context}

Generate the country-specific variables for the proposal template."""


def _strip_accents(text: str) -> str:
    """Strip accents/diacritics, keeping base ASCII characters.

    Prevents 'Education' -> 'E?ducation' in the PDF renderer.
    """
    nfkd = unicodedata.normalize("NFKD", text)
    return "".join(c for c in nfkd if not unicodedata.combining(c))


def _sanitize_country_variables(cv: CountryVariables) -> CountryVariables:
    """Ensure all program/brand names are ASCII-safe for PDF and
    country-owned school names never contain 'Alpha'."""
    cv.jv_program_name = _strip_accents(cv.jv_program_name)
    cv.cultural_program_name = _strip_accents(cv.cultural_program_name)
    cv.credential_phrase = _strip_accents(cv.credential_phrase)

    import re
    if re.search(r"\balpha\b", cv.jv_program_name, re.IGNORECASE):
        cleaned = re.sub(r"\s*\bAlpha\b\s*", " ", cv.jv_program_name).strip()
        cv.jv_program_name = cleaned if cleaned else f"{cv.country_adjective} Education"
        logger.warning(
            "Stripped 'Alpha' from jv_program_name -> %s",
            cv.jv_program_name,
        )

    jv_norm = cv.jv_program_name.lower().strip()
    cult_norm = cv.cultural_program_name.lower().strip()
    if jv_norm == cult_norm or jv_norm.startswith(cult_norm) or cult_norm.startswith(jv_norm):
        cv.cultural_program_name = f"{cv.country_adjective}Core"
        logger.warning(
            "jv_program_name and cultural_program_name overlapped; "
            "reset cultural_program_name -> %s",
            cv.cultural_program_name,
        )

    return cv


async def _generate_country_variables(
    target: str,
    country_profile: CountryProfile,
    education_analysis: EducationAnalysis,
    strategy: Strategy,
    financial_model: FinancialModel,
    per_student_budget: float,
    y5_students: int,
) -> CountryVariables:
    """Generate country-specific variables via LLM structured output."""
    # Build education context
    edu_parts: list[str] = []
    diag = education_analysis.system_diagnosis
    reform = education_analysis.reform_landscape
    if diag.primary_pain_points:
        edu_parts.append(
            "Student pain points: "
            + "; ".join(diag.primary_pain_points[:5])
        )
    if diag.parent_pain_points:
        edu_parts.append(
            "Parent pain points: "
            + "; ".join(diag.parent_pain_points[:5])
        )
    if reform.active_reforms:
        edu_parts.append(
            "Active reforms: "
            + "; ".join(reform.active_reforms[:5])
        )
    if reform.appetite_for_foreign_models:
        edu_parts.append(
            "Appetite for foreign models: "
            + str(reform.appetite_for_foreign_models)
        )

    # Build strategy context
    strat_parts: list[str] = []
    if strategy.entry_mode:
        strat_parts.append(
            f"Entry mode: {strategy.entry_mode.value}"
        )
    if strategy.partnership_structure.type:
        strat_parts.append(
            f"Partnership: {strategy.partnership_structure.type.value}"
        )
    if strategy.brand.jv_name_suggestion:
        strat_parts.append(
            f"Suggested JV name: {strategy.brand.jv_name_suggestion}"
        )
    if strategy.phased_rollout:
        for ph in strategy.phased_rollout[:3]:
            strat_parts.append(
                f"Phase: {ph.phase} ({ph.timeline}) "
                f"- {ph.student_count or 'TBD'} students"
            )

    # Format population/GDP safely
    demo = country_profile.demographics
    econ = country_profile.economy
    pop_str = (
        f"{demo.total_population:,.0f}"
        if demo.total_population else "N/A"
    )
    k12_str = (
        f"{country_profile.education.k12_enrolled:,.0f}"
        if country_profile.education.k12_enrolled else "N/A"
    )
    gdp_str = (
        f"{econ.gdp_per_capita:,.0f}"
        if econ.gdp_per_capita else "N/A"
    )

    prompt = COUNTRY_VARIABLES_PROMPT.format(
        target=target,
        population=pop_str,
        k12_students=k12_str,
        gdp_per_capita=gdp_str,
        ministry=(
            country_profile.regulatory.ministry_of_education or "N/A"
        ),
        head_of_state=(
            country_profile.political_context.head_of_state or "N/A"
        ),
        national_vision=(
            country_profile.political_context.national_vision_plan
            or "N/A"
        ),
        government_type=(
            country_profile.political_context.government_type or "N/A"
        ),
        per_student_budget=f"{per_student_budget:,.0f}",
        y5_students=f"{y5_students:,}",
        education_context="\n".join(edu_parts) or "N/A",
        strategy_context="\n".join(strat_parts) or "N/A",
    )

    try:
        result = await call_llm(
            system_prompt=prompt,
            user_prompt=(
                f"Generate the country-specific variables for {target}."
            ),
            output_schema=CountryVariables,
        )
        return _sanitize_country_variables(result)  # type: ignore
    except Exception as exc:
        logger.error(
            "Failed to generate country variables for %s: %s",
            target, exc,
        )
        # Fallback with sensible defaults
        adj = target.split()[-1] if " " in target else target
        return CountryVariables(
            country_adjective=adj,
            jv_program_name=f"{target} Education",
            cultural_program_name=f"{target}Core",
            credential_phrase=f"Educated in {target}",
            first_launch_city="the capital",
            second_city="major cities",
            language_subjects=(
                "National language, Social Studies, "
                "Civic Education, History"
            ),
            edu_llm_training=(
                f"{target} language, laws, customs, "
                "culture, and values"
            ),
            cultural_values=(
                f"{target} values, traditions, and aspirations"
            ),
            ministry_reference="Ministry of Education",
            regulatory_framework=(
                "national education regulatory framework"
            ),
            funding_mechanism=(
                "Government funding through public education budgets"
            ),
            national_credential_reference=(
                "leading national university"
            ),
            country_specific_overview=(
                f"{target} presents a significant opportunity "
                "for education transformation."
            ),
            school_infrastructure_note=(
                f"Schools will integrate with {target}'s "
                "existing educational infrastructure."
            ),
        )


# ---------------------------------------------------------------------------
# Term Sheet (Combined Proposal) Generation
# ---------------------------------------------------------------------------

async def generate_term_sheet(
    target: str,
    country_profile: CountryProfile,
    education_analysis: EducationAnalysis,
    strategy: Strategy,
    financial_model: FinancialModel,
    assumptions: FinancialAssumptions,
    term_sheet_assumptions: FinancialAssumptions | None = None,
) -> tuple[str, str, str]:
    """Generate a combined proposal document (term sheet + deal terms).

    Returns (summary_markdown, proposal_docx_path, jv_program_name).
    The DOCX is the primary deliverable — a professionally formatted
    document matching the Alpha_Ed71_Combined_Proposal benchmark.
    ``jv_program_name`` is the localized school-network brand name so
    downstream generators (e.g. the proposal deck) use the same name.
    """
    logger.info("Generating combined proposal for %s", target)

    # --- Extract deal parameters from term sheet assumptions ---
    ts: dict = {}
    if term_sheet_assumptions and term_sheet_assumptions.assumptions:
        ts = {
            item.key: item.value
            for item in term_sheet_assumptions.assumptions
        }

    per_student = ts.get("ts_per_student_budget", 25_000)
    pnl = financial_model.pnl_projection
    y5_students = int(ts.get(
        "ts_students_year5",
        pnl[-1].students if pnl else 100_000,
    ))

    # --- Generate country-specific variables ---
    cv = await _generate_country_variables(
        target, country_profile, education_analysis, strategy,
        financial_model, per_student, y5_students,
    )

    # --- Build the DOCX ---
    docx_path = _build_proposal_docx(
        target=target,
        cv=cv,
        financial_model=financial_model,
        assumptions=assumptions,
        ts=ts,
        strategy=strategy,
        country_profile=country_profile,
    )

    # --- Build a simple summary markdown for frontend ---
    summary_md = _build_summary_markdown(
        target, cv, ts, financial_model,
    )

    logger.info("Combined proposal generated for %s", target)
    return summary_md, docx_path, cv.jv_program_name


# ---------------------------------------------------------------------------
# DOCX Builder — template-based, matching benchmark format
# ---------------------------------------------------------------------------

def _build_proposal_docx(
    target: str,
    cv: CountryVariables,
    financial_model: FinancialModel,
    assumptions: FinancialAssumptions,
    ts: dict,
    strategy: Strategy,
    country_profile: CountryProfile,
) -> str:
    """Build the combined proposal DOCX matching benchmark.

    Part 1 (pages 1-5): Strategic partnership proposal narrative
    Part 2 (pages 6-7): Deal terms and financial tables
    """
    doc = DocxDocument()

    # --- Page setup ---
    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)

    # --- Configure styles ---
    _configure_styles(doc)

    # --- Extract key financial values ---
    fin = _extract_financial_values(financial_model, ts, strategy)

    # ===============================================================
    # PART 1: COMBINED PROPOSAL (Pages 1-5)
    # ===============================================================

    _add_confidential_header(doc, target, cv)
    _add_overview_section(doc, target, cv, fin)
    _add_transformation_section(doc, target, cv, fin)
    _add_cultural_program_section(doc, target, cv, fin)
    _add_school_network_section(doc, target, cv, fin, strategy)
    _add_halo_alpha_strategic_role_section(doc, target, cv)
    _add_future_opportunities_section(doc, target, cv)
    _add_sequencing_section(doc, target, cv, fin, strategy)
    _add_funding_section(doc, target, cv, fin)

    # ===============================================================
    # PART 2: DEAL TERMS (Pages 6-7)
    # ===============================================================

    doc.add_page_break()
    _add_confidential_header(doc, target, cv)
    _add_deal_terms_section(doc, target, cv, fin, financial_model)
    _add_school_design_section(
        doc, target, cv, fin, financial_model,
    )

    # --- Save ---
    output_dir = os.path.join(
        OUTPUT_DIR, target.lower().replace(" ", "_"),
    )
    os.makedirs(output_dir, exist_ok=True)
    fname = f"{target.replace(' ', '_')}_term_sheet.docx"
    path = os.path.join(output_dir, fname)
    doc.save(path)
    logger.info("Combined proposal DOCX saved: %s", path)
    return path


# ---------------------------------------------------------------------------
# Style Configuration
# ---------------------------------------------------------------------------

def _configure_styles(doc: DocxDocument) -> None:
    """Configure document styles to match the benchmark format."""
    # Default font
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = DocxPt(11)
    style.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
    style.paragraph_format.space_after = DocxPt(6)
    style.paragraph_format.line_spacing = 1.15

    # Heading 1: Section headers
    h1 = doc.styles["Heading 1"]
    h1.font.name = "Calibri"
    h1.font.size = DocxPt(16)
    h1.font.color.rgb = DocxRGB(0x1A, 0x1A, 0x2E)
    h1.font.bold = True
    h1.paragraph_format.space_before = DocxPt(18)
    h1.paragraph_format.space_after = DocxPt(8)

    # Heading 2
    h2 = doc.styles["Heading 2"]
    h2.font.name = "Calibri"
    h2.font.size = DocxPt(14)
    h2.font.color.rgb = DocxRGB(0x00, 0x6D, 0x77)
    h2.font.bold = True
    h2.paragraph_format.space_before = DocxPt(14)
    h2.paragraph_format.space_after = DocxPt(6)

    # List Bullet
    try:
        lb = doc.styles["List Bullet"]
        lb.font.name = "Calibri"
        lb.font.size = DocxPt(11)
        lb.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
    except KeyError:
        pass


# ---------------------------------------------------------------------------
# Financial Value Extraction
# ---------------------------------------------------------------------------

def _extract_financial_values(
    model: FinancialModel, ts: dict, strategy: Strategy,
) -> dict:
    """Extract all financial values needed for the template."""
    per_student = ts.get("ts_per_student_budget", 25_000)
    pnl = model.pnl_projection
    y5_students = int(ts.get(
        "ts_students_year5",
        pnl[-1].students if pnl else 100_000,
    ))
    num_schools = int(ts.get(
        "ts_num_schools",
        pnl[-1].schools if pnl else 10,
    ))

    # Upfront breakdown ($M)
    def _upfront(ts_key: str, model_val: float, default: int) -> float:
        return ts.get(
            ts_key,
            round(model_val / 1_000_000) if model_val > 0
            else default,
        )

    upfront_alphacore = _upfront(
        "ts_upfront_alphacore_license",
        model.upfront_alphacore_license, 250,
    )
    upfront_incept_edllm = _upfront(
        "ts_upfront_incept_edllm",
        model.upfront_incept_edllm, 250,
    )
    upfront_app_rd = _upfront(
        "ts_upfront_app_content_rd",
        model.upfront_app_content_rd, 250,
    )
    upfront_lifeskills = _upfront(
        "ts_upfront_lifeskills_rd",
        model.upfront_lifeskills_rd, 250,
    )
    upfront_mgmt = _upfront(
        "ts_upfront_mgmt_fee", model.upfront_mgmt_fee, 250,
    )
    upfront_timeback = _upfront(
        "ts_upfront_timeback_fee", model.upfront_timeback_fee, 500,
    )
    upfront_total = ts.get(
        "ts_upfront_ip_fee",
        (
            round(model.upfront_ip_fee / 1_000_000)
            if model.upfront_ip_fee > 1_000_000
            else model.upfront_ip_fee
        ),
    )

    # IP costs (AlphaCore + Incept EdLLM + EdTech Apps + Programs & LifeSkills)
    ip_development_total = (
        upfront_alphacore + upfront_incept_edllm
        + upfront_app_rd + upfront_lifeskills
    )
    fee_prepays_total = upfront_mgmt + upfront_timeback

    mgmt_pct = int(ts.get(
        "ts_management_fee_pct",
        round(model.management_fee_pct * 100),
    ))
    timeback_pct = int(ts.get(
        "ts_timeback_license_pct",
        round(model.timeback_license_pct * 100),
    ))

    # Ongoing costs
    per_student_mgmt = round(per_student * mgmt_pct / 100)
    per_student_timeback = round(per_student * timeback_pct / 100)

    # Annual revenue at scale
    annual_revenue_at_scale = y5_students * per_student

    # Funding gap: $25K per student less current public funding
    current_public_spend = min(15_000, per_student * 0.6)
    funding_gap_per_student = per_student - current_public_spend
    funding_gap_annual_100k = round(
        100_000 * funding_gap_per_student / 1_000_000_000, 1,
    )

    # Parent Education / Launch / Guide Training: fixed $50M/yr per rules
    parent_education_annual = ts.get("ts_parent_education_annual", 50)
    launch_capital_annual = ts.get("ts_launch_capital", parent_education_annual)

    # Cumulative students for IP amortization
    cumulative_students = 0
    if pnl:
        cumulative_students = sum(p.students for p in pnl)
    ip_amort_per_student = (
        round(ip_development_total * 1_000_000 / max(1, cumulative_students))
        if cumulative_students else 0
    )

    # Scaling plan
    scaling_plan: list[dict] = []
    if strategy.phased_rollout:
        for ph in strategy.phased_rollout[:5]:
            scaling_plan.append({
                "phase": ph.phase or "",
                "timeline": ph.timeline or "",
                "students": ph.student_count or 0,
            })
    elif pnl:
        for p in pnl:
            scaling_plan.append({
                "phase": f"Year {p.year}",
                "timeline": f"SY{26 + p.year - 1}-{27 + p.year - 1}",
                "students": p.students,
            })

    # --- National student commitment (excludes flagship) ---
    national_students = int(
        model.national_students
        if model.national_students
        else 100_000
    )

    # --- Flagship data (from optimization result or assumptions) ---
    flagship_opt = model.flagship_optimization
    flagship_tuition = model.flagship_tuition or 0
    flagship_students_total = model.flagship_students or 0

    # Derive schools and per-school from optimization metros
    if flagship_opt and flagship_opt.total_schools > 0:
        flagship_schools = flagship_opt.total_schools
        flagship_per_school = flagship_opt.optimal_capacity
    else:
        # Fallback: use term-sheet assumptions → financial model defaults
        flagship_schools = int(ts.get("ts_num_flagship_schools", 3))
        if flagship_schools == 0:
            flagship_schools = 3  # Ensure we always show something
        flagship_per_school = (
            flagship_students_total // max(1, flagship_schools)
            if flagship_students_total and flagship_schools
            else 500  # Default from financial_rules_v1.md fallback
        )
        # Ensure tuition has a sensible fallback
        if flagship_tuition == 0:
            flagship_tuition = int(ts.get("ts_flagship_tuition", 65_000))

    return {
        "per_student": per_student,
        "y5_students": y5_students,
        "national_students": national_students,
        "num_schools": num_schools,
        "upfront_alphacore": upfront_alphacore,
        "upfront_incept_edllm": upfront_incept_edllm,
        "upfront_app_rd": upfront_app_rd,
        "upfront_lifeskills": upfront_lifeskills,
        "upfront_mgmt": upfront_mgmt,
        "upfront_timeback": upfront_timeback,
        "upfront_total": upfront_total,
        "ip_development_total": ip_development_total,
        "fee_prepays_total": fee_prepays_total,
        "mgmt_pct": mgmt_pct,
        "timeback_pct": timeback_pct,
        "per_student_mgmt": per_student_mgmt,
        "per_student_timeback": per_student_timeback,
        "annual_revenue_at_scale": annual_revenue_at_scale,
        "funding_gap_per_student": funding_gap_per_student,
        "funding_gap_annual_100k": funding_gap_annual_100k,
        "current_public_spend": current_public_spend,
        "parent_education_annual": parent_education_annual,
        "launch_capital_annual": launch_capital_annual,
        "ip_amort_per_student": ip_amort_per_student,
        "cumulative_students": cumulative_students,
        "scaling_plan": scaling_plan,
        "pnl": model.pnl_projection or [],
        # Flagship data
        "flagship_tuition": flagship_tuition,
        "flagship_students_total": flagship_students_total,
        "flagship_schools": flagship_schools,
        "flagship_per_school": flagship_per_school,
        "flagship_optimization": flagship_opt,
    }


# ---------------------------------------------------------------------------
# Document Section Builders (Part 1: Proposal Narrative)
# ---------------------------------------------------------------------------

def _add_confidential_header(
    doc: DocxDocument, target: str, cv: CountryVariables,
) -> None:
    """Add the confidential header line matching the benchmark."""
    p = doc.add_paragraph()
    date_str = datetime.now().strftime("%m.%d.%Y")
    run = p.add_run(
        f"CONFIDENTIAL \u2013 Alpha Holdings - {target} "
        f"Strategic Partnership "
        f"(\u201c{cv.jv_program_name}\u201d) - {date_str}"
    )
    run.font.size = DocxPt(10)
    run.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)


def _add_overview_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
) -> None:
    """Build the Overview section (benchmark pages 1-2)."""
    doc.add_heading("Overview", level=1)

    # P1: Universal boilerplate
    _add_body(
        doc,
        "The AI world that is coming requires us to reinvent the "
        "educational system if we want to prepare our children & "
        "society to thrive. Alpha is the only one in the world "
        "building a national scale system that will transform every "
        "aspect of a student\u2019s educational journey from the "
        "ground up, including the student day, the teachers, the "
        "curriculum, and all of the technology.",
    )

    # P2: Country-specific credential phrase
    _add_body(
        doc,
        "The same way that Alpha has become known as the "
        "\u201cStanford of K-12\u201d, via our partnership, we are "
        "dedicated to making "
        f"\u201c{cv.credential_phrase}\u201d "
        "the most valuable credential for the next generation of "
        "global leaders.",
    )

    # P3: Partnership description with financials
    upfront_b = (
        fin["upfront_total"] / 1000
        if fin["upfront_total"] >= 1000
        else fin["upfront_total"]
    )
    scale_word = (
        "multi-billion-dollar" if upfront_b >= 1
        else f"${fin['upfront_total']:,.0f}M"
    )
    _add_body(
        doc,
        f"{cv.jv_program_name} is a {scale_word} partnership "
        f"between {target} and Alpha Holdings to build the "
        "world\u2019s first AI-native K\u201312 system at national "
        "scale. Our promise is clear and proven: students will love "
        "school, learn 2x faster, and develop life skills for the "
        "AI age.",
    )

    # P4: Cultural program introduction
    _add_body(
        doc,
        f"Together we will design {cv.cultural_program_name}, the "
        f"life-skills engine that ensures every "
        f"{cv.country_adjective} student loves school and thrives "
        f"in the AI age. {cv.cultural_program_name} is intended to "
        f"be {target}\u2019s most valuable education asset, "
        f"designed as {target}\u2019s equivalent to AlphaCore.",
    )

    # P5: Architecture description
    _add_body(
        doc,
        f"The {cv.jv_program_name} architecture is implemented "
        "through a national network of privately-operated, "
        "government-funded schools on the Alpha education system, "
        "with Alpha as exclusive initial operating partner. These "
        f"schools operate within the {cv.regulatory_framework}, "
        "ensuring full regulatory compliance while delivering "
        "transformational outcomes.",
    )

    # P6: Immediacy
    _add_body(
        doc,
        f"{cv.jv_program_name} launches immediately. Superior "
        "outcomes create unstoppable parent demand, and "
        f"{target} inherits a proven model for national "
        "transformation.",
    )

    # P7: Educational sovereignty
    _add_body(
        doc,
        f"By building {cv.jv_program_name} on top of Alpha\u2019s "
        f"complete infrastructure, {target} gains control of its "
        "educational sovereignty in the AI era and establishes the "
        f"global standard. {cv.jv_program_name} is operated by "
        "Alpha Holdings, the most experienced education company "
        "in the world.",
    )

    # P8: Country-specific overview
    if cv.country_specific_overview:
        _add_body(doc, cv.country_specific_overview)


def _add_transformation_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
) -> None:
    """Build the Transformation Steps section (pages 2-3)."""
    doc.add_heading(
        "Transformation Steps and Alpha\u2019s Proven Capabilities",
        level=1,
    )

    _add_body(
        doc,
        "Education transformation starts with three core truths: "
        "(i) kids should love school more than going on vacation, "
        "(ii) kids can crush academics in 2 hours per day and "
        "(iii) the key to your child\u2019s happiness, character, "
        "grit, and life success are the non-academic skills they "
        "learn outside the classroom.",
    )

    _add_body(
        doc,
        "Timeback, the AI and learning-science platform, compresses "
        "academic work into efficient mastery-based sessions "
        "tailored to each student, and gives each the rest of their "
        "day back. That time is then invested in project-based life "
        "skills \u2013 STEM, sports, arts, leadership, teamwork "
        "\u2013 that build character and capability.",
    )

    _add_body(
        doc,
        "Alpha brings a complete, already-operating capability "
        f"stack that {cv.jv_program_name} can license and adapt "
        "rather than inventing from scratch.",
    )

    # Capability bullet points (bold prefix)
    capabilities = [
        (
            "Reinvented school day: ",
            "from 6 hours of classes to 2 hours of academic mastery "
            "and 4 hours of project-based life skills development.",
        ),
        (
            "Timeback: ",
            "the AI and learning-science platform that delivers "
            "academic mastery 10x faster than conventional "
            "classrooms.",
        ),
        (
            "AlphaCore: ",
            "an AI-age life-skills curriculum that structures how "
            "students practice leadership, teamwork, communication, "
            "resilience, and other non-academic capabilities that "
            "matter in adult life. Alpha students love school, with "
            "a +93 NPS, and are accelerating academically by 2x in "
            "standardized tests.",
        ),
        (
            "Guides: ",
            "complete redefinition of the teachers\u2019 role, as "
            "a guide, coach, and mentor",
        ),
        (
            "Guide School: ",
            "the talent academy for training guides that mentor and "
            "motivate students while holding them to high standards.",
        ),
        (
            "Incept eduLLM: ",
            "the base learning-science large language model from "
            "Incept Labs, is the only LLM that has been "
            "specifically trained with Alpha\u2019s learning "
            "science, and is able to create an unending stream of "
            "personalized content for every student using Timeback.",
        ),
        (
            "Marketing: ",
            "A parent education and marketing engine, built on the "
            "belief that transformation fails if parents do not "
            "understand and demand the outcomes available for their "
            "children.",
        ),
    ]
    for bold_prefix, rest in capabilities:
        _add_list_item_bold_prefix(doc, bold_prefix, rest)

    _add_body(
        doc,
        "Alpha has deployed this stack across multiple physical "
        "school models, including Sports academies, gt.school for "
        "gifted and talented students, wilderness training school, "
        "and eSports. Across these formats, the core academic + "
        "life-skills structure delivers consistent, measurable "
        "results.",
    )

    _add_body(
        doc,
        f"This complete infrastructure is what "
        f"{cv.jv_program_name} licenses, adapts, and embeds into "
        f"a {cv.country_adjective}-owned system.",
    )


def _add_cultural_program_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
) -> None:
    """Build the Cultural Program and Education Assets section."""
    doc.add_heading(
        f"The Newly Created {cv.cultural_program_name} Program and "
        f"{target} Education Assets",
        level=1,
    )

    _add_body(
        doc,
        "A country\u2019s most valuable educational asset is its "
        "K\u201312 life-skills program; whoever designs it is "
        "effectively writing the operating system for the next "
        "generation of leaders.",
    )

    _add_body(
        doc,
        f"Through {cv.jv_program_name}, we will create "
        f"{cv.cultural_program_name}, the {cv.country_adjective} "
        "parallel to AlphaCore: the core national identity and "
        f"life-skills program to transform every "
        f"{cv.country_adjective} student\u2019s childhood. "
        f"{cv.cultural_program_name} is intended to be "
        f"{target}\u2019s most powerful education asset, fully "
        f"under {cv.country_adjective} control.",
    )

    _add_body(
        doc,
        f"Within {cv.jv_program_name}, the {cv.country_adjective} "
        "layer sits on top of Alpha\u2019s global technology and "
        f"IP stack and is owned in {target}. The key components of "
        f"this {cv.country_adjective} layer are:",
    )

    _add_list_item_bold_prefix(
        doc,
        f"{cv.cultural_program_name} design: ",
        "We start from the AlphaCore base and co-create "
        f"{cv.cultural_program_name}, the {cv.country_adjective} "
        "life-skills system just as powerful and fully under "
        f"{cv.country_adjective} control to encode "
        f"{cv.cultural_values}.",
    )

    _add_list_item_bold_prefix(
        doc,
        f"{target}-specific EdTech applications ",
        "that integrate into Timeback, including "
        f"{cv.language_subjects}.",
    )

    _add_list_item_bold_prefix(
        doc,
        f"A specialized {target} eduLLM configuration, ",
        f"trained on {cv.edu_llm_training}, built on top of "
        "Incept\u2019s base eduLLM.",
    )

    _add_body(
        doc,
        "The base eduLLM from Incept Labs provides the "
        "learning-science engine and the ability to generate an "
        "unending stream of personalized content for every student "
        f"using Timeback. The {target}-specialized eduLLM ensures "
        "all content is culturally and linguistically appropriate.",
    )

    _add_body(
        doc,
        f"With {cv.cultural_program_name}, {target} apps, and the "
        f"{target}-specialized eduLLM layered on top, {target} "
        "gains true educational sovereignty over what students "
        "learn and what information is put into their heads.",
    )


def _add_school_network_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    strategy: Strategy,
) -> None:
    """Build the School Network section."""
    doc.add_heading(
        f"{cv.jv_program_name} School Network", level=1,
    )

    _add_body(
        doc,
        f"{cv.jv_program_name} is a {target}-owned national "
        "education platform, with Alpha Holdings, Inc. "
        "as the exclusive operating partner under a long-term "
        "management and IP license agreement. "
        f"{cv.jv_program_name} licenses the global technology "
        "stack (Timeback, AlphaCore, Guide School, eduLLM) and "
        f"adapts it with the {cv.country_adjective} cultural "
        "layer.",
    )

    _add_body(
        doc,
        "We are proposing to implement through a national network "
        "of privately-operated, government-funded schools, but are "
        "equally open to other structures.",
    )

    _add_body(
        doc,
        f"{cv.jv_program_name} and Alpha will jointly design and "
        f"open a family of {cv.jv_program_name} school formats "
        "across the country designed to be accessible to all "
        f"{cv.country_adjective} students. Every "
        f"{cv.jv_program_name} school runs on Alpha\u2019s "
        f"Timeback with {cv.cultural_program_name}, delivering "
        "the three student commitments.",
    )

    _add_body(
        doc,
        f"{cv.jv_program_name} will invest in school development "
        "and launch activities, including national consumer "
        "marketing and enrollment infrastructure, so that each new "
        "school type opens with strong parent demand. "
        f"{cv.school_infrastructure_note}",
    )

    _add_body(
        doc,
        f"{cv.jv_program_name} schools target a "
        f"${fin['per_student']:,.0f} per student annual budget, "
        "with an indicative annual budget of "
        f"${fin['annual_revenue_at_scale'] / 1_000_000_000:.1f}B+ "
        "at scale.",
    )

    _add_body(
        doc,
        f"{cv.jv_program_name} is designed to launch immediately "
        "once the framework is agreed. Superior outcomes create "
        "parent demand and a strong political tailwind for "
        "adoption.",
    )

    nat = fin["national_students"]
    broader_market = int(nat * 1.5)
    _add_body(
        doc,
        f"A staged scaling plan targets {nat:,} "
        f"{cv.country_adjective} students by Year 5, with a "
        f"broader market opportunity of {broader_market:,}+ "
        "students:",
    )

    # Scaling plan bullets
    if fin["scaling_plan"]:
        for sp in fin["scaling_plan"]:
            students_text = (
                f"{sp['students']:,} students"
                if sp["students"] else "TBD"
            )
            _add_list_item(
                doc, f"{sp['timeline']}: {students_text}",
            )
    elif fin["pnl"]:
        for p in fin["pnl"]:
            _add_list_item(
                doc,
                f"Year {p.year}: {p.students:,} students "
                f"across {p.schools} schools",
            )


def _add_halo_alpha_strategic_role_section(
    doc: DocxDocument, target: str, cv: CountryVariables,
) -> None:
    """Build the Strategic Role of Alpha Flagship Schools section.

    Explains why flagship Alpha schools are essential to the
    country/state expansion proposal — placed in the main body
    (Part 1) between the school network and future opportunities.
    """
    doc.add_heading(
        "Strategic Role of Alpha Flagship Schools", level=1,
    )

    _add_body(
        doc,
        "Alpha Flagship Schools are 100% owned by Alpha Holdings, "
        "Inc. and serve as the premium \u201chalo brand\u201d "
        "\u2014 flagship schools that demonstrate the full Alpha "
        "experience at the highest level of execution.",
    )

    _add_body(
        doc,
        f"The Alpha Flagship Schools are considered essential to the "
        f"{target} expansion proposal because they act as the apex "
        "brand that anchors the entire education system and generates "
        "a necessary \u201chalo effect\u201d for the rest of the "
        "portfolio.",
    )

    _add_list_item_bold_prefix(
        doc,
        "Marketing and Validation Engine: ",
        "These schools serve as a marketing and validation engine. "
        "By establishing an unassailable benchmark for excellence, "
        "they legitimize the brand\u2019s entire presence in "
        f"{target}.",
    )

    _add_list_item_bold_prefix(
        doc,
        "Justification for Premium Positioning: ",
        "The flagship schools create a brand halo that justifies "
        "premium pricing across the entire portfolio, including the "
        f"Alpha-branded schools and {cv.jv_program_name} "
        "country-owned/Alpha-operated schools.",
    )

    _add_list_item_bold_prefix(
        doc,
        "Strategic Anchor for National Transformation: ",
        "The flagship presence is essential to the entire "
        "proposal\u2019s success because it anchors the system and "
        "provides the proof of concept required for a national-scale "
        "education transformation.",
    )

    _add_body(
        doc,
        "In summary, the Alpha Flagship Schools are the high-profile "
        "\u201cgold standard\u201d institutions meant to drive demand "
        "and trust for the broader, larger-scale expansion.",
    )


def _add_future_opportunities_section(
    doc: DocxDocument, target: str, cv: CountryVariables,
) -> None:
    """Build the Future Opportunities section."""
    doc.add_heading(
        "Future Alpha and Regional Opportunities", level=1,
    )

    _add_body(
        doc,
        f"Alpha-branded private schools in {target}, regional "
        "expansion, and private-pay offerings are intentionally "
        "treated as follow-on opportunities. They can be structured "
        "as separate arrangements and are not required for "
        f"{cv.jv_program_name} to succeed.",
    )


def _add_sequencing_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    strategy: Strategy,
) -> None:
    """Build the High-level Sequencing Plan (UAE benchmark)."""
    doc.add_heading("High-level Sequencing Plan", level=1)

    # Extract student counts for phase descriptions (national commitment)
    nat = fin["national_students"]
    phase1_students = nat // 20   # ~5% of target
    phase2_mid = nat // 4         # ~25% of target
    phase2_high = nat // 2        # ~50% of target

    # Launch school year
    launch_sy_start = 26  # SY26-27 as baseline
    launch_sy = f"SY{launch_sy_start}-{launch_sy_start + 1}"

    # Always use the detailed template matching UAE benchmark
    phases = [
        (
            "Phase 0 (Months 1-12): ",
            f"IP Transfer, {cv.cultural_program_name} design, "
            "and eduLLM model training.",
        ),
        (
            "Phase 1 (Months 9-18): ",
            f"Launch of 1-2 {cv.jv_program_name} schools in "
            f"{cv.first_launch_city} in {launch_sy} under "
            f"{cv.regulatory_framework} by taking over existing "
            "Model Schools.",
        ),
        (
            "Phase 2 (Months 12-36): ",
            f"National rollout of the {cv.jv_program_name} school "
            f"network to {phase1_students:,}, then "
            f"{phase2_mid:,}, then {phase2_high:,}+ students.",
        ),
        (
            "Phase 3 (Year 3+): ",
            "Continued scaling, with optional follow-on regional "
            "and private-pay expatriate expansions.",
        ),
    ]

    for bold_part, rest in phases:
        _add_list_item_bold_prefix(doc, bold_part, rest)


def _add_funding_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
) -> None:
    """Build the Funding, Investment, and Real Estate section."""
    doc.add_heading(
        "Funding, Investment, and Real Estate", level=1,
    )

    _add_body(
        doc,
        "We are flexible on structure and will work to adapt the "
        "commercial framework to align with "
        f"{target}\u2019s preferred ownership, governance, "
        "and funding model.",
    )

    ip_total_m = fin["ip_development_total"]
    _add_body(
        doc,
        f"{cv.jv_program_name} will require ${ip_total_m:,.0f} "
        "million of upfront development capital across four areas, "
        "plus prepaid fees. Ownership of all resulting "
        f"{target}-specific IP will reside with "
        f"{cv.jv_program_name}. The breakdown is as follows:",
    )

    _add_list_item(
        doc,
        f"${fin['upfront_alphacore']:,.0f} million — Alpha Core License "
        f"for use in {target}.",
    )
    _add_list_item(
        doc,
        f"${fin.get('upfront_incept_edllm', 250):,.0f} million — "
        f"Country-specific Incept EdLLM, trained on "
        f"{cv.edu_llm_training}.",
    )
    _add_list_item(
        doc,
        f"${fin['upfront_lifeskills']:,.0f} million — "
        f"Country-specific Programs and Life Skills "
        f"({cv.cultural_program_name}).",
    )
    _add_list_item(
        doc,
        f"${fin['upfront_app_rd']:,.0f} million — "
        f"Country-specific EdTech Apps on "
        f"Timeback ({cv.language_subjects}).",
    )

    _add_body(
        doc,
        "There is a simple, scalable commercial structure between "
        f"Alpha Holdings and {cv.jv_program_name}.",
    )

    # Fee structure bullets
    mgmt_min = max(2_500, fin["per_student_mgmt"])
    timeback_min = max(5_000, fin["per_student_timeback"])
    # per_student and y5 available via fin dict if needed downstream
    _ = fin["per_student"], fin["y5_students"]

    _add_list_item_bold_prefix(
        doc, "Operating Fee: ",
        f"{fin['mgmt_pct']}% of funding/tuition, with a "
        f"${mgmt_min:,.0f} per-student annual minimum.",
    )

    _add_list_item_bold_prefix(
        doc, "Timeback Fee: ",
        f"{fin['timeback_pct']}% of funding/tuition, with a "
        f"${timeback_min:,.0f} per-student annual minimum "
        "(same pricing as for existing Alpha schools globally).",
    )

    _add_list_item(
        doc,
        "Alpha Holdings will receive upfront prepaid fees: "
        f"${fin['upfront_timeback']:,.0f}M Timeback + "
        f"${fin['upfront_mgmt']:,.0f}M Operating Fee "
        f"(total ${fin['fee_prepays_total']:,.0f}M).",
    )

    _add_list_item_bold_prefix(
        doc, "Parent Education / Launch / Guide Training: ",
        f"${fin.get('parent_education_annual', 50):,.0f}M per year, "
        "ongoing each year.",
    )

    _add_body(
        doc,
        "Initial capitalization and fee prepayments amount to "
        f"roughly ${fin['upfront_total']:,.0f}M in upfront capital "
        f"requirements for {cv.jv_program_name}.",
    )

    _add_body(
        doc,
        "To ensure schools open at quality and scale rather than "
        "as small pilots, the framework includes launch funding, "
        "scholarships, and guarantees. This scholarship and "
        "guarantee structure de-risks enrollment for the initial "
        "years.",
    )

    _add_list_item(
        doc,
        f"{cv.jv_program_name} provides school launch activities, "
        "including parent education, marketing, and enrollment and "
        "guide recruiting infrastructure, expected to be on the "
        f"order of ${fin['launch_capital_annual']:,.0f} million "
        "per year during the initial launch phase.",
    )

    _add_list_item(doc, cv.funding_mechanism)

    _add_list_item(
        doc,
        "School funding will be allocated across schools as they "
        "open, creating a stable demand base from day one and "
        "enabling each campus to open at full quality.",
    )

    _add_list_item(doc, cv.school_infrastructure_note)


# ---------------------------------------------------------------------------
# Document Section Builders (Part 2: Deal Terms)
# ---------------------------------------------------------------------------

def _add_deal_terms_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    model: FinancialModel,
) -> None:
    """Build the deal terms section with the investment table.

    Table 2: Country/State Owned Schools — Investment Required
    """
    doc.add_heading(
        f"1. {cv.jv_program_name} Schools "
        f"(Country/State Owned, Alpha Operated)",
        level=1,
    )

    _add_list_item(
        doc,
        f"100% {target} owned, 0% Alpha owned. "
        "Alpha operates on behalf of the Country/State.",
    )
    _add_list_item(
        doc,
        f"Per student funding/tuition: ${fin['per_student']:,.0f}/year.",
    )
    _add_list_item(
        doc,
        f"Minimum {fin['national_students']:,} students per year commitment.",
    )
    _add_list_item(
        doc,
        "Schools can be operated as either public or private schools.",
    )
    _add_list_item(
        doc,
        "Country/State is responsible for sourcing real estate; schools pay rent.",
    )

    doc.add_paragraph()  # spacer

    # --- Table 2: Investment Table ---
    doc.add_heading("Investment Required", level=2)
    _add_investment_table(doc, cv, fin)

    doc.add_paragraph()  # spacer

    # --- Table 1: School Cost Comparison ---
    doc.add_heading("School Cost Comparison", level=2)
    _add_body(
        doc,
        "Illustrative \u201ccost to educate\u201d per student for "
        f"{cv.jv_program_name} school vs. traditional school at "
        f"${fin['per_student'] / 1000:.0f}k annual budget:",
    )
    _add_cost_comparison_table(doc, fin)


def _add_school_design_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    model: FinancialModel,
) -> None:
    """Build the Flagship Alpha section with summary table.

    Table 3: Alpha Flagships — Key Metrics
    """
    doc.add_heading("2. Alpha Flagship Schools", level=1)

    _add_body(
        doc,
        "Alpha Flagship Schools are 100% owned by Alpha Holdings, Inc. and serve as the premium "
        "\"halo brand\" \u2014 flagship schools that demonstrate the full Alpha experience at "
        "the highest level of execution. They establish Alpha\u2019s reputation in each market, "
        "set the benchmark for academic and life-skills outcomes, and create aspirational demand "
        "that drives enrollment across the broader national school network. "
        "Sized as 250-, 500-, or 1,000-student schools.",
    )

    flagship_opt = fin.get("flagship_optimization")

    _add_list_item(
        doc,
        "Flagship schools operate at 25% operating margin.",
    )

    # Tuition / capacity may vary per metro — show range when they differ
    if flagship_opt and flagship_opt.metros:
        tuitions = [mr.tuition for mr in flagship_opt.metros]
        capacities = [mr.capacity_per_school for mr in flagship_opt.metros]
        if len(set(tuitions)) == 1:
            tuition_str = f"${tuitions[0]:,.0f}/year"
        else:
            tuition_str = (
                f"${min(tuitions):,.0f} – ${max(tuitions):,.0f}/year "
                "(varies by metro)"
            )
        if len(set(capacities)) == 1:
            capacity_str = f"{capacities[0]:,} students per school"
        else:
            capacity_str = (
                f"{min(capacities):,} – {max(capacities):,} "
                "students per school (varies by metro)"
            )
    else:
        tuition_str = f"${fin.get('flagship_tuition', 0):,.0f}/year"
        capacity_str = (
            f"{fin.get('flagship_per_school', 0):,} students per school"
        )

    _add_list_item(doc, f"Tuition: {tuition_str}.")
    _add_list_item(doc, f"Capacity: {capacity_str}.")
    _add_list_item(
        doc,
        "Country/State provides 50% capacity backstop for 5 years.",
    )

    # If no metros qualified, note the scholarship requirement
    if flagship_opt and flagship_opt.scholarship_needed:
        doc.add_paragraph()
        _add_body(doc, flagship_opt.scholarship_note)

    doc.add_paragraph()  # spacer

    # --- Table 3: Alpha Flagship Summary ---
    doc.add_heading("Flagship Key Metrics", level=2)
    _add_flagship_summary_table(doc, cv, fin, model)


# ---------------------------------------------------------------------------
# Table Builders
# ---------------------------------------------------------------------------

def _add_cost_comparison_table(
    doc: DocxDocument, fin: dict,
) -> None:
    """Add the school cost comparison table (Table 1).

    Per financial_rules_v1.md — fixed per-student cost breakdown at $25K.
    Compares Traditional school vs Alpha/Timeback model.
    """
    budget = fin["per_student"]  # Should be $25,000

    # --- Fixed cost breakdown from financial_rules_v1.md ---
    alpha_guides = 4_500
    alpha_programs = 4_250
    alpha_other_hc = 1_750
    alpha_facility = 3_000
    alpha_misc = 1_500
    alpha_timeback = 5_000       # 20% of $25K
    alpha_operating_fee = 2_500  # 10% of $25K
    alpha_margin_ip = 2_500      # Operating Margin / Amortization of IP
    alpha_total = (
        alpha_guides + alpha_programs + alpha_other_hc
        + alpha_facility + alpha_misc + alpha_timeback
        + alpha_operating_fee + alpha_margin_ip
    )

    # --- Traditional school estimate at same budget ---
    trad_teachers = round(budget * 0.50)   # ~50% teachers/staff
    trad_curriculum = round(budget * 0.08)
    trad_admin = round(budget * 0.12)
    trad_facility = round(budget * 0.20)
    trad_misc = round(budget * 0.10)
    trad_total = (
        trad_teachers + trad_curriculum + trad_admin
        + trad_facility + trad_misc
    )

    headers = [
        "Cost Item (Per Student)",
        f"Traditional ${budget / 1000:.0f}k School",
        f"Alpha/Timeback ${budget / 1000:.0f}k School",
    ]
    rows = [
        [
            "Funding/Tuition",
            f"${budget:,.0f}", f"${budget:,.0f}",
        ],
        [
            "Teachers / Guides",
            f"${trad_teachers:,.0f}", f"${alpha_guides:,.0f}",
        ],
        [
            "Programs and Life Skills",
            f"${trad_curriculum:,.0f}", f"${alpha_programs:,.0f}",
        ],
        [
            "Other Headcount",
            f"${trad_admin:,.0f}", f"${alpha_other_hc:,.0f}",
        ],
        [
            "Facility / CapEx",
            f"${trad_facility:,.0f}", f"${alpha_facility:,.0f}",
        ],
        [
            "Miscellaneous Expenses",
            f"${trad_misc:,.0f}", f"${alpha_misc:,.0f}",
        ],
        [
            "Timeback (Software)",
            "$0", f"${alpha_timeback:,.0f}",
        ],
        [
            "Operating Fee (10%)",
            "$0", f"${alpha_operating_fee:,.0f}",
        ],
        [
            "Operating Margin / IP Amort",
            "$0", f"${alpha_margin_ip:,.0f}",
        ],
        [
            "Total",
            f"${trad_total:,.0f}", f"${alpha_total:,.0f}",
        ],
        [
            "Education Outcomes",
            "Current Baseline", "World Class (2x faster, +93 NPS)",
        ],
    ]

    _add_styled_table(doc, headers, rows, bold_last_row=True)


def _add_investment_table(
    doc: DocxDocument, cv: CountryVariables, fin: dict,
) -> None:
    """Add the investment table for Country/State Owned Schools (Table 2).

    Per financial_rules_v1.md — shows upfront and ongoing investment required.
    """
    mgmt_pct = fin["mgmt_pct"]
    tb_pct = fin["timeback_pct"]
    per_student = fin["per_student"]
    national_students = fin["national_students"]  # National commitment (100K)
    parent_ed = fin.get("parent_education_annual", 50)
    scholarship_gap = fin.get("funding_gap_per_student", 0)

    # Calculate ongoing annual fees at scale (based on national commitment)
    ongoing_timeback = round(
        national_students * per_student * (tb_pct / 100) / 1_000_000
    )
    ongoing_operating = round(
        national_students * per_student * (mgmt_pct / 100) / 1_000_000
    )
    ongoing_scholarship = round(
        national_students * scholarship_gap / 1_000_000
    )

    headers = [
        "Investment Item",
        "Upfront ($M)",
        "Ongoing ($M/yr)",
        "Notes",
    ]

    sep_upfront = "Upfront Development Costs (FIXED — do not scale by country)"
    sep_prepaid = "Prepaid Fees (scale by student commitment)"
    sep_ongoing = "Ongoing Annual Costs (scale above 100,000 students)"

    rows = [
        # --- Separator: Upfront ---
        [sep_upfront, sep_upfront, sep_upfront, sep_upfront],
        [
            "Alpha Core License",
            f"${fin['upfront_alphacore']:,.0f}",
            "",
            "Paid upfront to Alpha Holdings",
        ],
        [
            "Country-Specific Incept EdLLM",
            f"${fin['upfront_incept_edllm']:,.0f}",
            "",
            "Paid upfront",
        ],
        [
            "Country-Specific Programs & Life Skills",
            f"${fin['upfront_lifeskills']:,.0f}",
            "",
            "Paid upfront",
        ],
        [
            "Country-Specific EdTech Apps",
            f"${fin['upfront_app_rd']:,.0f}",
            "",
            "Paid upfront",
        ],
        # --- Separator: Prepaid ---
        [sep_prepaid, sep_prepaid, sep_prepaid, sep_prepaid],
        [
            "Timeback (Prepaid)",
            f"${fin['upfront_timeback']:,.0f}",
            "",
            f"{national_students:,} students x ${5_000:,}/student",
        ],
        [
            "Operating Fee (Prepaid)",
            f"${fin['upfront_mgmt']:,.0f}",
            "",
            f"{national_students:,} students x ${2_500:,}/student",
        ],
        # --- Separator: Ongoing ---
        [sep_ongoing, sep_ongoing, sep_ongoing, sep_ongoing],
        [
            "Parent Education / Launch / Guides",
            "",
            f"${parent_ed:,.0f}",
            "Per year, ongoing",
        ],
        [
            "Scholarships / Increased Public Funding",
            "",
            f"${ongoing_scholarship:,.0f}" if ongoing_scholarship > 0 else "TBD",
            f"${per_student:,} - current public funding/student",
        ],
        [
            f"Timeback ({tb_pct}% of funding/tuition)",
            "",
            f"${ongoing_timeback:,.0f}",
            f"Min ${5_000:,}/student/year, ongoing",
        ],
        [
            f"Operating Fee ({mgmt_pct}% of funding/tuition)",
            "",
            f"${ongoing_operating:,.0f}",
            f"Min ${2_500:,}/student/year, ongoing",
        ],
        # --- Total ---
        [
            "TOTAL UPFRONT",
            f"${fin['upfront_total']:,.0f}",
            "",
            f"${fin['ip_development_total']:,.0f}M dev + ${fin['fee_prepays_total']:,.0f}M prepaid",
        ],
    ]

    _add_styled_table(doc, headers, rows, bold_last_row=True)


def _add_flagship_summary_table(
    doc: DocxDocument, cv: CountryVariables,
    fin: dict, model: FinancialModel,
) -> None:
    """Add the Alpha Flagship Schools summary table (Table 3).

    Uses the optimization result when available — shows real metro names,
    data-driven school counts, capacity, and tuition from the grid search.
    Falls back to synthetic rows when no optimization data exists.
    """
    flagship_opt = fin.get("flagship_optimization")
    flagship_tuition = fin.get("flagship_tuition", 0)
    flagship_schools = fin.get("flagship_schools", 0)
    flagship_per_school = fin.get("flagship_per_school", 0)

    if flagship_tuition == 0 or flagship_schools == 0:
        _add_body(
            doc,
            "Alpha Flagship School details to be determined based on "
            "metro-level AGI analysis.",
        )
        return

    headers = [
        "Metro",
        "Schools",
        "Students / School",
        "Tuition / Year",
        "Annual Revenue",
    ]

    rows: list[list[str]] = []
    total_schools = 0
    total_students = 0
    total_revenue = 0

    # --- Build metro rows from optimization result ---
    if flagship_opt and flagship_opt.metros:
        for mr in flagship_opt.metros:
            metro_students = mr.schools * mr.capacity_per_school
            total_schools += mr.schools
            total_students += metro_students
            total_revenue += mr.annual_revenue
            rows.append([
                mr.metro_name,
                str(mr.schools),
                f"{mr.capacity_per_school:,}",
                f"${mr.tuition:,.0f}",
                f"${mr.annual_revenue / 1_000_000:.0f}M",
            ])
    else:
        # Fallback: distribute schools across capital + other metros
        capital_schools = min(3, flagship_schools)
        remaining = flagship_schools - capital_schools

        _fallback_metros = [
            (cv.first_launch_city or "Capital City", capital_schools),
        ]
        if remaining >= 1 and cv.second_city:
            _fallback_metros.append((cv.second_city, 1))
            remaining -= 1
        if remaining >= 1:
            _fallback_metros.append(("Third Metro", remaining))

        for metro_name, n_schools in _fallback_metros:
            metro_students = n_schools * flagship_per_school
            rev = metro_students * flagship_tuition
            total_schools += n_schools
            total_students += metro_students
            total_revenue += rev
            rows.append([
                metro_name,
                str(n_schools),
                f"{flagship_per_school:,}",
                f"${flagship_tuition:,.0f}",
                f"${rev / 1_000_000:.0f}M",
            ])

    # Total row — show tuition only if uniform across metros
    tuition_values = [mr.tuition for mr in flagship_opt.metros] if (
        flagship_opt and flagship_opt.metros
    ) else []
    if tuition_values and len(set(tuition_values)) == 1:
        total_tuition_str = f"${tuition_values[0]:,.0f}"
    elif tuition_values:
        total_tuition_str = (
            f"${min(tuition_values):,.0f} – "
            f"${max(tuition_values):,.0f}"
        )
    else:
        total_tuition_str = f"${flagship_tuition:,.0f}"
    rows.append([
        "TOTAL",
        str(total_schools),
        f"{total_students:,} total",
        total_tuition_str,
        f"${total_revenue / 1_000_000:.0f}M",
    ])

    _add_styled_table(doc, headers, rows, bold_last_row=True)


# ---------------------------------------------------------------------------
# Table Rendering Helper
# ---------------------------------------------------------------------------

def _add_styled_table(
    doc: DocxDocument,
    headers: list[str],
    rows: list[list[str]],
    bold_last_row: bool = False,
) -> None:
    """Add a professionally styled table to the document.

    Matches the benchmark format: header row with accent background,
    alternating row shading, clean borders.
    """
    num_cols = len(headers)
    num_rows = len(rows) + 1  # +1 for header

    table = doc.add_table(rows=num_rows, cols=num_cols)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Prevent rows from breaking across pages and keep table together
    total_rows = len(table.rows)
    for row_idx, row in enumerate(table.rows):
        tr = row._tr
        tr_pr = tr.get_or_add_trPr()
        tr_pr.append(tr_pr.makeelement(qn("w:cantSplit"), {}))
        is_last_row = row_idx == total_rows - 1
        for cell in row.cells:
            for p in cell.paragraphs:
                p.paragraph_format.keep_together = True
                if not is_last_row:
                    p.paragraph_format.keep_with_next = True

    # --- Header row ---
    for ci, header_text in enumerate(headers):
        cell = table.rows[0].cells[ci]
        paras = cell.paragraphs
        p = paras[0] if paras else cell.add_paragraph()
        p.paragraph_format.space_before = DocxPt(2)
        p.paragraph_format.space_after = DocxPt(2)
        run = p.add_run(header_text)
        run.bold = True
        run.font.name = "Calibri"
        run.font.size = DocxPt(9)
        run.font.color.rgb = DocxRGB(0xFF, 0xFF, 0xFF)
        # Accent background
        tc = cell._element
        tc_pr = tc.get_or_add_tcPr()
        shading_el = tc_pr.makeelement(qn("w:shd"), {
            qn("w:fill"): "006D77",
            qn("w:val"): "clear",
        })
        tc_pr.append(shading_el)

    # --- Data rows ---
    for ri, row_data in enumerate(rows):
        is_separator = (
            bool(row_data)
            and len(set(row_data)) == 1
            and len(row_data[0]) > 20
        )
        is_last = (ri == len(rows) - 1)

        if is_separator:
            # Merge all cells into one separator row
            first_cell = table.rows[ri + 1].cells[0]
            last_cell = table.rows[ri + 1].cells[num_cols - 1]
            merged = first_cell.merge(last_cell)
            paras = merged.paragraphs
            p = paras[0] if paras else merged.add_paragraph()
            p.paragraph_format.space_before = DocxPt(2)
            p.paragraph_format.space_after = DocxPt(2)
            run = p.add_run(row_data[0])
            run.font.name = "Calibri"
            run.font.size = DocxPt(8)
            run.font.color.rgb = DocxRGB(0x66, 0x66, 0x66)
            run.italic = True
            # Light background
            tc = merged._element
            tc_pr = tc.get_or_add_tcPr()
            shading_el = tc_pr.makeelement(qn("w:shd"), {
                qn("w:fill"): "E8E8E8",
                qn("w:val"): "clear",
            })
            tc_pr.append(shading_el)
            continue

        for ci in range(num_cols):
            cell_text = (
                row_data[ci] if ci < len(row_data) else ""
            )
            cell = table.rows[ri + 1].cells[ci]
            paras = cell.paragraphs
            p = paras[0] if paras else cell.add_paragraph()
            p.paragraph_format.space_before = DocxPt(2)
            p.paragraph_format.space_after = DocxPt(2)

            is_bold = (
                (bold_last_row and is_last)
                or cell_text.startswith("**")
            )
            display_text = (
                cell_text.strip("*")
                if cell_text.startswith("**") else cell_text
            )
            run = p.add_run(display_text)
            run.font.name = "Calibri"
            run.font.size = DocxPt(9)
            run.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
            run.bold = is_bold

            # Alternating row shading
            if ri % 2 == 1:
                tc = cell._element
                tc_pr = tc.get_or_add_tcPr()
                shading_el = tc_pr.makeelement(qn("w:shd"), {
                    qn("w:fill"): "F5F5F5",
                    qn("w:val"): "clear",
                })
                tc_pr.append(shading_el)

    doc.add_paragraph("")  # Spacer after table


# ---------------------------------------------------------------------------
# Paragraph / List Item Helpers
# ---------------------------------------------------------------------------

def _add_body(doc: DocxDocument, text: str) -> None:
    """Add a normal body paragraph."""
    p = doc.add_paragraph(text)
    p.style = doc.styles["Normal"]


def _add_list_item(doc: DocxDocument, text: str) -> None:
    """Add a bullet list item."""
    doc.add_paragraph(text, style="List Bullet")


def _add_list_item_bold_prefix(
    doc: DocxDocument, bold_part: str, rest: str,
) -> None:
    """Add a bullet with bold prefix then normal text.

    e.g. "**Timeback:** the AI platform..."
    """
    p = doc.add_paragraph(style="List Bullet")
    run_bold = p.add_run(bold_part)
    run_bold.bold = True
    run_bold.font.name = "Calibri"
    run_bold.font.size = DocxPt(11)
    p.add_run(rest)


# ---------------------------------------------------------------------------
# Summary Markdown (for frontend display)
# ---------------------------------------------------------------------------

def _build_summary_markdown(
    target: str, cv: CountryVariables,
    ts: dict, model: FinancialModel,
) -> str:
    """Build a summary markdown string for frontend display."""
    per_student = ts.get("ts_per_student_budget", 25_000)
    pnl = model.pnl_projection
    y5_students = int(ts.get(
        "ts_students_year5",
        pnl[-1].students if pnl else 100_000,
    ))
    upfront = ts.get(
        "ts_upfront_ip_fee",
        (
            round(model.upfront_ip_fee / 1_000_000)
            if model.upfront_ip_fee > 1_000_000
            else model.upfront_ip_fee
        ),
    )
    mgmt_fee = ts.get("ts_management_fee_pct", 10)
    tb_fee = ts.get("ts_timeback_license_pct", 20)

    lines = [
        f"# {cv.jv_program_name} \u2014 Combined Proposal",
        f"## Alpha Holdings, Inc. \u00d7 {target}",
        "",
        f"**Program Name:** {cv.jv_program_name}",
        f"**Cultural Program:** {cv.cultural_program_name}",
        f"**Credential:** {cv.credential_phrase}",
        "",
        "### Key Terms",
        f"- **Upfront Ask:** ${upfront:,.0f}M",
        f"- **Per-Student Budget:** ${per_student:,.0f}",
        f"- **Year 5 Students:** {y5_students:,}",
        f"- **Management Fee:** {mgmt_fee}%",
        f"- **Timeback License:** {tb_fee}%",
        "",
        "### Scaling Plan",
    ]

    if pnl:
        for p in pnl:
            lines.append(
                f"- Year {p.year}: {p.students:,} students | "
                f"{p.schools} schools | ${p.revenue:,.0f} revenue"
            )

    lines.extend([
        "",
        "*This proposal document is confidential and non-binding. "
        "All terms are subject to final negotiation and execution "
        "of definitive agreements.*",
    ])

    return "\n".join(lines)
