"""Term Sheet Generator — produces a professional combined proposal DOCX.

Modelled on the Alpha_Ed71_Combined_Proposal.docx benchmark document:
  Part 1 (pages 1-5): Strategic partnership proposal narrative
  Part 2 (pages 6-7): Deal terms and financial tables

~70% of the document is boilerplate matching the UAE benchmark.
~30% is country/state-specific content generated by the LLM.

Includes a HITL gate for term sheet assumptions (deal terms)
that the user can review/adjust before the term sheet is generated.
Changes to key financial terms trigger financial model recalculation.
"""

from __future__ import annotations

import json
import logging
import os
import unicodedata
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from docx import Document as DocxDocument
from docx.shared import Pt as DocxPt, RGBColor as DocxRGB, Inches as DocxInches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

from models.schemas import (
    CountryProfile, EducationAnalysis, Strategy,
    FinancialModel, FinancialAssumptions, FinancialAssumption, TargetType,
)
from services.llm import call_llm, call_llm_plain
from config import OUTPUT_DIR

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Term Sheet Assumptions Generator (unchanged — supports HITL gates)
# ---------------------------------------------------------------------------

# Keys that overlap with the financial model and require recalculation
FINANCIAL_MODEL_OVERLAP_KEYS = {
    "ts_upfront_ip_fee",
    "ts_upfront_alphacore_license",
    "ts_upfront_app_content_rd",
    "ts_upfront_lifeskills_rd",
    "ts_upfront_mgmt_fee",
    "ts_upfront_timeback_fee",
    "ts_management_fee_pct",
    "ts_timeback_license_pct",
    "ts_students_year5",
    "ts_per_student_budget",
    "ts_capex_per_school",
}

# Mapping from term sheet assumption keys to financial model assumption keys
TS_TO_FM_KEY_MAP = {
    "ts_upfront_ip_fee": "upfront_ip_fee",
    "ts_upfront_alphacore_license": "upfront_alphacore_license",
    "ts_upfront_app_content_rd": "upfront_app_content_rd",
    "ts_upfront_lifeskills_rd": "upfront_lifeskills_rd",
    "ts_upfront_mgmt_fee": "upfront_mgmt_fee",
    "ts_upfront_timeback_fee": "upfront_timeback_fee",
    "ts_management_fee_pct": "management_fee_pct",
    "ts_timeback_license_pct": "timeback_license_pct",
    "ts_students_year5": "students_year5",
    "ts_per_student_budget": "per_student_budget",
    "ts_capex_per_school": "capex_per_school",
}


def generate_term_sheet_assumptions(
    target: str,
    country_profile: CountryProfile,
    strategy: Strategy,
    financial_model: FinancialModel,
    financial_assumptions: FinancialAssumptions,
) -> FinancialAssumptions:
    """Generate a set of configurable term sheet assumptions for HITL review.

    These are the deal-specific terms that will appear in the term sheet.
    Some overlap with the financial model — if user changes those, a
    recalculation of the financial model is required.
    """
    logger.info("Generating term sheet assumptions for %s", target)

    # Pull current values from financial model/assumptions
    fa = {item.key: item.value for item in financial_assumptions.assumptions}

    mgmt_pct = round(financial_model.management_fee_pct * 100)
    timeback_pct = round(financial_model.timeback_license_pct * 100)
    upfront_ip = financial_model.upfront_ip_fee
    upfront_ip_m = round(upfront_ip / 1_000_000) if upfront_ip > 1_000_000 else upfront_ip

    # Student targets from financial model
    y5_students = 0
    if financial_model.pnl_projection:
        y5_students = financial_model.pnl_projection[-1].students

    y5_revenue = 0
    if financial_model.pnl_projection:
        y5_revenue = financial_model.pnl_projection[-1].revenue

    per_student = fa.get("per_student_budget", fa.get("mid_tuition", 20_000))
    capex_per_school = fa.get("capex_per_school", 5_000_000)

    # Calculate backstop based on UAE formula: 50% capacity × tuition × schools × 5 years
    num_schools = financial_model.pnl_projection[-1].schools if financial_model.pnl_projection else 10
    backstop_annual = round(0.5 * y5_students * per_student / 1_000_000)  # $M
    mgmt_fee_prepay_m = round(min(5000, y5_students) * per_student * (mgmt_pct / 100) * 2 / 1_000_000)

    is_us_state = country_profile.target.type == TargetType.US_STATE

    assumptions = [
        # --- Deal Structure ---
        FinancialAssumption(
            key="ts_partnership_type",
            label="Partnership Structure",
            value=1,  # 1=JV, 2=Licensing, 3=Direct
            min_val=1, max_val=3, step=1,
            unit="type", category="deal",
            description="1 = Joint Venture, 2 = Licensing, 3 = Direct Operation",
        ),
        FinancialAssumption(
            key="ts_alpha_ownership_pct",
            label="Alpha Ownership / Control (%)",
            value=0 if not is_us_state else 100,
            min_val=0, max_val=100, step=1,
            unit="%", category="deal",
            description="Alpha's equity stake in the JV. 0% = Operator & Licensor model (UAE structure). 100% for direct.",
        ),
        FinancialAssumption(
            key="ts_term_years",
            label="Partnership Term (years)",
            value=25, min_val=10, max_val=50, step=5,
            unit="years", category="deal",
            description="Initial partnership duration (renewable)",
        ),
        FinancialAssumption(
            key="ts_exclusivity_years",
            label="Exclusivity Period (years)",
            value=25, min_val=5, max_val=50, step=5,
            unit="years", category="deal",
            description="Alpha has exclusive rights to the 2hr Learning model in the territory",
        ),

        # --- Upfront Payment Breakdown (overlaps with financial model) ---
        FinancialAssumption(
            key="ts_upfront_alphacore_license",
            label="AlphaCore License ($M)",
            value=round(financial_model.upfront_alphacore_license / 1_000_000) if financial_model.upfront_alphacore_license > 1_000_000 else round(financial_model.upfront_alphacore_license),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description="AlphaCore curriculum OS and learning management system license",
        ),
        FinancialAssumption(
            key="ts_upfront_app_content_rd",
            label="Customized Country-Specific App Content R&D ($M)",
            value=round(financial_model.upfront_app_content_rd / 1_000_000) if financial_model.upfront_app_content_rd > 1_000_000 else round(financial_model.upfront_app_content_rd),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description="R&D for country-specific EdTech app content and localization",
        ),
        FinancialAssumption(
            key="ts_upfront_lifeskills_rd",
            label="Customized Country-Specific LifeSkills R&D ($M)",
            value=round(financial_model.upfront_lifeskills_rd / 1_000_000) if financial_model.upfront_lifeskills_rd > 1_000_000 else round(financial_model.upfront_lifeskills_rd),
            min_val=10, max_val=500, step=10,
            unit="$M", category="fees",
            description="R&D for country-specific life skills curriculum (AsasCore equivalent)",
        ),
        FinancialAssumption(
            key="ts_upfront_mgmt_fee",
            label="Upfront Management Fee ($M)",
            value=round(financial_model.upfront_mgmt_fee / 1_000_000) if financial_model.upfront_mgmt_fee > 1_000_000 else max(1, round(financial_model.upfront_mgmt_fee)),
            min_val=1, max_val=500, step=5,
            unit="$M", category="fees",
            description="Target Students Y5 × Per-Student Budget × 10%",
        ),
        FinancialAssumption(
            key="ts_upfront_timeback_fee",
            label="Upfront Timeback Fee ($M)",
            value=round(financial_model.upfront_timeback_fee / 1_000_000) if financial_model.upfront_timeback_fee > 1_000_000 else max(1, round(financial_model.upfront_timeback_fee)),
            min_val=1, max_val=1000, step=5,
            unit="$M", category="fees",
            description="Target Students Y5 × Per-Student Budget × 20%",
        ),
        FinancialAssumption(
            key="ts_upfront_ip_fee",
            label="Total Upfront Ask ($M)",
            value=upfront_ip_m,
            min_val=5, max_val=2000, step=5,
            unit="$M", category="fees",
            description="Sum of all upfront components. Changes recalculate financial model.",
        ),
        FinancialAssumption(
            key="ts_management_fee_pct",
            label="Management Fee (% of school revenue)",
            value=mgmt_pct,
            min_val=5, max_val=20, step=1,
            unit="%", category="fees",
            description="Alpha's ongoing management fee. 10% floor is non-negotiable.",
            locked=True,
        ),
        FinancialAssumption(
            key="ts_timeback_license_pct",
            label="Timeback License (% of per-student budget)",
            value=timeback_pct,
            min_val=10, max_val=30, step=1,
            unit="%", category="fees",
            description="Alpha's technology/IP licensing fee. 20% floor is non-negotiable.",
            locked=True,
        ),
        FinancialAssumption(
            key="ts_mgmt_fee_prepay_years",
            label="Management Fee Prepayment (years)",
            value=2, min_val=0, max_val=5, step=1,
            unit="years", category="fees",
            description="Years of management fee prepaid at signing",
        ),
        FinancialAssumption(
            key="ts_mgmt_fee_prepay_amount",
            label="Management Fee Prepayment Amount ($M)",
            value=max(1, mgmt_fee_prepay_m),
            min_val=0, max_val=500, step=5,
            unit="$M", category="fees",
            description="Calculated: first-year students x per-student budget x mgmt fee % x prepay years",
        ),

        # --- School Portfolio (overlaps with financial model) ---
        FinancialAssumption(
            key="ts_students_year5",
            label="Year 5 Student Target",
            value=y5_students,
            min_val=1000, max_val=500_000, step=5000,
            unit="students", category="school_portfolio",
            description="Target enrollment at scale. Changes recalculate financial model.",
        ),
        FinancialAssumption(
            key="ts_per_student_budget",
            label="Per-Student Annual Tuition / Budget ($)",
            value=round(per_student),
            min_val=5_000, max_val=100_000, step=500,
            unit="$", category="school_portfolio",
            description="Blended annual tuition per student. Changes recalculate financial model.",
        ),
        FinancialAssumption(
            key="ts_num_flagship_schools",
            label="Flagship Alpha Schools",
            value=2, min_val=0, max_val=10, step=1,
            unit="schools", category="school_portfolio",
            description="Premium flagship schools ($100K+ tuition) for halo effect",
        ),
        FinancialAssumption(
            key="ts_flagship_tuition",
            label="Flagship School Tuition ($)",
            value=100_000 if not is_us_state else 50_000,
            min_val=25_000, max_val=200_000, step=5_000,
            unit="$", category="school_portfolio",
            description="Annual tuition for flagship Alpha schools",
        ),
        FinancialAssumption(
            key="ts_num_schools",
            label="Total Schools at Scale",
            value=num_schools,
            min_val=1, max_val=500, step=5,
            unit="schools", category="school_portfolio",
            description="Total number of schools in the network at Year 5",
        ),

        # --- Counterparty Commitments ---
        FinancialAssumption(
            key="ts_scholarship_backstop_annual",
            label="Scholarship / Tuition Backstop ($M/year)",
            value=max(1, backstop_annual),
            min_val=0, max_val=2000, step=10,
            unit="$M", category="commitments",
            description="Annual backstop: 50% capacity x tuition (per UAE formula)",
        ),
        FinancialAssumption(
            key="ts_backstop_years",
            label="Backstop Commitment Period (years)",
            value=5, min_val=3, max_val=10, step=1,
            unit="years", category="commitments",
            description="Duration of the scholarship/tuition backstop commitment",
        ),
        FinancialAssumption(
            key="ts_launch_capital",
            label="Launch / Marketing Capital ($M)",
            value=max(5, round(y5_revenue * 0.05 / 1_000_000)),
            min_val=1, max_val=500, step=5,
            unit="$M", category="commitments",
            description="Counterparty's commitment to launch capital and marketing",
        ),
        FinancialAssumption(
            key="ts_capex_per_school",
            label="CapEx per School Buildout ($M)",
            value=round(capex_per_school / 1_000_000, 1),
            min_val=0.5, max_val=20, step=0.5,
            unit="$M", category="school_portfolio",
            description="Capital expenditure per new school. Changes recalculate financial model.",
        ),
    ]

    return FinancialAssumptions(assumptions=assumptions)


def get_financial_model_adjustments(
    term_sheet_adjustments: dict[str, float],
) -> dict[str, float]:
    """Given term sheet adjustments, return any that require financial model recalculation.

    Returns a dict of financial model assumption key -> new value.
    """
    fm_adjustments = {}
    for ts_key, new_val in term_sheet_adjustments.items():
        if ts_key in TS_TO_FM_KEY_MAP:
            fm_key = TS_TO_FM_KEY_MAP[ts_key]
            if ts_key == "ts_capex_per_school":
                new_val = new_val * 1_000_000  # Convert from $M to $
            fm_adjustments[fm_key] = new_val
    return fm_adjustments


# ---------------------------------------------------------------------------
# Country-Specific Variables — structured LLM output
# ---------------------------------------------------------------------------

class CountryVariables(BaseModel):
    """Country-specific content that gets inserted into the proposal template.

    ~30% of the proposal document varies by country. This model captures
    all the country-specific text variables needed for template substitution.
    """
    country_adjective: str = Field(description="National adjective, e.g. 'French', 'Saudi', 'Brazilian'")
    jv_program_name: str = Field(description="Partnership program name (equivalent of 'Ed71' for UAE). Short, memorable, 2-4 words max. MUST use only plain ASCII characters (no accents, no diacritics). Example: 'Ed71', 'Education 2030', 'Alpha France' — NOT 'Éducation 2030'.")
    cultural_program_name: str = Field(description="Country's life-skills curriculum program name (equivalent of 'AsasCore' for UAE). 1-2 words, culturally resonant. MUST use only plain ASCII characters (no accents, no diacritics). Example: 'AsasCore', 'Savoir' — NOT 'Éducation'.")
    credential_phrase: str = Field(description="Prestige education credential phrase, e.g. 'Educated in the Emirates'. Format: 'Educated in [Country]'")
    first_launch_city: str = Field(description="Best city to launch first schools (capital or major education hub)")
    second_city: str = Field(description="Second city for expansion")
    language_subjects: str = Field(description="Country-specific education app subjects needing localization (equivalent of 'Arabic, Islamic Studies, Social Studies, ESL for Arabic speakers'). Comma-separated list of 4-5 subjects.")
    edu_llm_training: str = Field(description="What the country-specific eduLLM would be trained on (equivalent of 'UAE language, laws, customs, culture, and values'). Short phrase.")
    cultural_values: str = Field(description="What the cultural program would encode (equivalent of 'Emirati values, habits, and aspirations'). Short phrase.")
    ministry_reference: str = Field(description="Name of the relevant education authority/ministry")
    regulatory_framework: str = Field(description="How schools would operate under local law (equivalent of 'ADEK / Ministry frameworks')")
    funding_mechanism: str = Field(description="How student funding would work in this country (1-2 sentences)")
    national_credential_reference: str = Field(description="A prestige local institution for comparison (equivalent of 'NYU Abu Dhabi')")
    country_specific_overview: str = Field(description="2-3 sentences about why this country is ripe for education transformation. Reference specific national plans, reforms, or challenges.")
    school_infrastructure_note: str = Field(description="1 sentence about how schools will integrate with existing infrastructure")


COUNTRY_VARIABLES_PROMPT = """You are preparing a strategic education partnership proposal between
Alpha Holdings / 2hr Learning and {target}. This proposal will be presented to the head of state
and senior government decision-makers.

You need to generate country-specific content variables that will be inserted into a standardized
proposal template (modelled on the UAE Ed71 deal structure).

Every value must be culturally appropriate, factually accurate, and diplomatically calibrated for
a head-of-state audience. The program names should sound local, prestigious, and aspirational.

Country Context:
- Population: {population}
- K-12 Students: {k12_students}
- GDP per capita: ${gdp_per_capita}
- Education ministry: {ministry}
- Head of state: {head_of_state}
- National vision/plan: {national_vision}
- Government type: {government_type}
- Per-student budget for this deal: ${per_student_budget}
- Year 5 student target: {y5_students}

Education Context:
{education_context}

Strategy Context:
{strategy_context}

Generate the country-specific variables for the proposal template."""


def _strip_accents(text: str) -> str:
    """Strip accents/diacritics from text, keeping base ASCII characters.

    Prevents 'Éducation' → 'E?ducation' in the PDF renderer.
    """
    nfkd = unicodedata.normalize("NFKD", text)
    return "".join(c for c in nfkd if not unicodedata.combining(c))


def _sanitize_country_variables(cv: CountryVariables) -> CountryVariables:
    """Ensure all program/brand names are ASCII-safe for PDF rendering."""
    cv.jv_program_name = _strip_accents(cv.jv_program_name)
    cv.cultural_program_name = _strip_accents(cv.cultural_program_name)
    cv.credential_phrase = _strip_accents(cv.credential_phrase)
    return cv


async def _generate_country_variables(
    target: str,
    country_profile: CountryProfile,
    education_analysis: EducationAnalysis,
    strategy: Strategy,
    financial_model: FinancialModel,
    per_student_budget: float,
    y5_students: int,
) -> CountryVariables:
    """Generate country-specific variables via LLM structured output."""

    # Build education context
    edu_parts = []
    if education_analysis.system_diagnosis.primary_pain_points:
        edu_parts.append("Student pain points: " + "; ".join(education_analysis.system_diagnosis.primary_pain_points[:5]))
    if education_analysis.system_diagnosis.parent_pain_points:
        edu_parts.append("Parent pain points: " + "; ".join(education_analysis.system_diagnosis.parent_pain_points[:5]))
    if education_analysis.reform_landscape.active_reforms:
        edu_parts.append("Active reforms: " + "; ".join(education_analysis.reform_landscape.active_reforms[:5]))
    if education_analysis.reform_landscape.appetite_for_foreign_models:
        edu_parts.append(f"Appetite for foreign models: {education_analysis.reform_landscape.appetite_for_foreign_models}")

    # Build strategy context
    strat_parts = []
    if strategy.entry_mode:
        strat_parts.append(f"Entry mode: {strategy.entry_mode.value}")
    if strategy.partnership_structure.type:
        strat_parts.append(f"Partnership: {strategy.partnership_structure.type.value}")
    if strategy.brand.jv_name_suggestion:
        strat_parts.append(f"Suggested JV name: {strategy.brand.jv_name_suggestion}")
    if strategy.phased_rollout:
        for ph in strategy.phased_rollout[:3]:
            strat_parts.append(f"Phase: {ph.phase} ({ph.timeline}) - {ph.student_count or 'TBD'} students")

    prompt = COUNTRY_VARIABLES_PROMPT.format(
        target=target,
        population=f"{country_profile.demographics.total_population:,.0f}" if country_profile.demographics.total_population else "N/A",
        k12_students=f"{country_profile.education.k12_enrolled:,.0f}" if country_profile.education.k12_enrolled else "N/A",
        gdp_per_capita=f"{country_profile.economy.gdp_per_capita:,.0f}" if country_profile.economy.gdp_per_capita else "N/A",
        ministry=country_profile.regulatory.ministry_of_education or "N/A",
        head_of_state=country_profile.political_context.head_of_state or "N/A",
        national_vision=country_profile.political_context.national_vision_plan or "N/A",
        government_type=country_profile.political_context.government_type or "N/A",
        per_student_budget=f"{per_student_budget:,.0f}",
        y5_students=f"{y5_students:,}",
        education_context="\n".join(edu_parts) or "N/A",
        strategy_context="\n".join(strat_parts) or "N/A",
    )

    try:
        result = await call_llm(
            system_prompt=prompt,
            user_prompt=f"Generate the country-specific variables for {target}.",
            output_schema=CountryVariables,
        )
        return _sanitize_country_variables(result)  # type: ignore[return-value]
    except Exception as exc:
        logger.error("Failed to generate country variables for %s: %s", target, exc)
        # Fallback with sensible defaults
        return CountryVariables(
            country_adjective=target.split()[-1] if " " in target else target,
            jv_program_name=f"Alpha {target}",
            cultural_program_name=f"{target}Core",
            credential_phrase=f"Educated in {target}",
            first_launch_city="the capital",
            second_city="major cities",
            language_subjects=f"National language, Social Studies, Civic Education, History",
            edu_llm_training=f"{target} language, laws, customs, culture, and values",
            cultural_values=f"{target} values, traditions, and aspirations",
            ministry_reference="Ministry of Education",
            regulatory_framework="national education regulatory framework",
            funding_mechanism="Government funding through public education budgets",
            national_credential_reference="leading national university",
            country_specific_overview=f"{target} presents a significant opportunity for education transformation.",
            school_infrastructure_note=f"Schools will integrate with {target}'s existing educational infrastructure.",
        )


# ---------------------------------------------------------------------------
# Term Sheet (Combined Proposal) Generation
# ---------------------------------------------------------------------------

async def generate_term_sheet(
    target: str,
    country_profile: CountryProfile,
    education_analysis: EducationAnalysis,
    strategy: Strategy,
    financial_model: FinancialModel,
    assumptions: FinancialAssumptions,
    term_sheet_assumptions: FinancialAssumptions | None = None,
) -> tuple[str, str]:
    """Generate a combined proposal document (term sheet + deal terms).

    Returns (summary_markdown, proposal_docx_path).
    The DOCX is the primary deliverable — a professionally formatted document
    matching the Alpha_Ed71_Combined_Proposal benchmark.
    """
    logger.info("Generating combined proposal for %s", target)

    # --- Extract deal parameters from term sheet assumptions ---
    ts = {}
    if term_sheet_assumptions and term_sheet_assumptions.assumptions:
        ts = {item.key: item.value for item in term_sheet_assumptions.assumptions}

    per_student = ts.get("ts_per_student_budget", 25_000)
    y5_students = int(ts.get("ts_students_year5",
                              financial_model.pnl_projection[-1].students if financial_model.pnl_projection else 100_000))

    # --- Generate country-specific variables ---
    cv = await _generate_country_variables(
        target, country_profile, education_analysis, strategy,
        financial_model, per_student, y5_students,
    )

    # --- Build the DOCX ---
    docx_path = _build_proposal_docx(
        target=target,
        cv=cv,
        financial_model=financial_model,
        assumptions=assumptions,
        ts=ts,
        strategy=strategy,
        country_profile=country_profile,
    )

    # --- Build a simple summary markdown (for frontend display if needed) ---
    summary_md = _build_summary_markdown(target, cv, ts, financial_model)

    logger.info("Combined proposal generated for %s", target)
    return summary_md, docx_path


# ---------------------------------------------------------------------------
# DOCX Builder — template-based, matching benchmark format
# ---------------------------------------------------------------------------

def _build_proposal_docx(
    target: str,
    cv: CountryVariables,
    financial_model: FinancialModel,
    assumptions: FinancialAssumptions,
    ts: dict,
    strategy: Strategy,
    country_profile: CountryProfile,
) -> str:
    """Build the full combined proposal DOCX matching the Alpha_Ed71 benchmark.

    Part 1 (pages 1-5): Strategic partnership proposal narrative
    Part 2 (pages 6-7): Deal terms and financial tables
    """
    doc = DocxDocument()

    # --- Page setup ---
    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)

    # --- Configure styles ---
    _configure_styles(doc)

    # --- Extract key financial values ---
    fin = _extract_financial_values(financial_model, ts, strategy)

    # ===================================================================
    # PART 1: COMBINED PROPOSAL (Pages 1-5)
    # ===================================================================

    # Confidential header
    _add_confidential_header(doc, target, cv)

    # Section 1: Overview
    _add_overview_section(doc, target, cv, fin)

    # Section 2: Transformation Steps and Alpha's Proven Capabilities
    _add_transformation_section(doc, target, cv, fin)

    # Section 3: The Newly Created Cultural Program and Education Assets
    _add_cultural_program_section(doc, target, cv, fin)

    # Section 4: School Network
    _add_school_network_section(doc, target, cv, fin, strategy)

    # Section 5: Future Alpha and Regional Opportunities
    _add_future_opportunities_section(doc, target, cv)

    # Section 6: High-level Sequencing Plan
    _add_sequencing_section(doc, target, cv, fin, strategy)

    # Section 7: Funding, Investment, and Real Estate
    _add_funding_section(doc, target, cv, fin)

    # ===================================================================
    # PART 2: DEAL TERMS (Pages 6-7)
    # ===================================================================

    doc.add_page_break()

    # Confidential header (repeated for Part 2)
    _add_confidential_header(doc, target, cv)

    # Section 8: Ed71 Schools (deal terms + tables)
    _add_deal_terms_section(doc, target, cv, fin, financial_model)

    # Section 9: School Design (with per-student P&L table)
    _add_school_design_section(doc, target, cv, fin, financial_model)

    # --- Save ---
    output_dir = os.path.join(OUTPUT_DIR, target.lower().replace(" ", "_"))
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, f"{target.replace(' ', '_')}_term_sheet.docx")
    doc.save(path)
    logger.info("Combined proposal DOCX saved: %s", path)
    return path


# ---------------------------------------------------------------------------
# Style Configuration
# ---------------------------------------------------------------------------

def _configure_styles(doc: DocxDocument) -> None:
    """Configure document styles to match the benchmark format."""
    # Default font
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = DocxPt(11)
    style.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
    style.paragraph_format.space_after = DocxPt(6)
    style.paragraph_format.line_spacing = 1.15

    # Heading 1: Section headers
    h1 = doc.styles["Heading 1"]
    h1.font.name = "Calibri"
    h1.font.size = DocxPt(16)
    h1.font.color.rgb = DocxRGB(0x1a, 0x1a, 0x2e)
    h1.font.bold = True
    h1.paragraph_format.space_before = DocxPt(18)
    h1.paragraph_format.space_after = DocxPt(8)

    # Heading 2
    h2 = doc.styles["Heading 2"]
    h2.font.name = "Calibri"
    h2.font.size = DocxPt(14)
    h2.font.color.rgb = DocxRGB(0x00, 0x6D, 0x77)
    h2.font.bold = True
    h2.paragraph_format.space_before = DocxPt(14)
    h2.paragraph_format.space_after = DocxPt(6)

    # List Bullet
    try:
        lb = doc.styles["List Bullet"]
        lb.font.name = "Calibri"
        lb.font.size = DocxPt(11)
        lb.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
    except KeyError:
        pass


# ---------------------------------------------------------------------------
# Financial Value Extraction
# ---------------------------------------------------------------------------

def _extract_financial_values(
    model: FinancialModel, ts: dict, strategy: Strategy
) -> dict:
    """Extract all financial values needed for the template."""

    per_student = ts.get("ts_per_student_budget", 25_000)
    y5_students = int(ts.get("ts_students_year5",
                              model.pnl_projection[-1].students if model.pnl_projection else 100_000))
    num_schools = int(ts.get("ts_num_schools", model.pnl_projection[-1].schools if model.pnl_projection else 10))

    # Upfront breakdown ($M)
    upfront_alphacore = ts.get("ts_upfront_alphacore_license",
                                round(model.upfront_alphacore_license / 1_000_000) if model.upfront_alphacore_license > 0 else 250)
    upfront_app_rd = ts.get("ts_upfront_app_content_rd",
                             round(model.upfront_app_content_rd / 1_000_000) if model.upfront_app_content_rd > 0 else 250)
    upfront_lifeskills = ts.get("ts_upfront_lifeskills_rd",
                                 round(model.upfront_lifeskills_rd / 1_000_000) if model.upfront_lifeskills_rd > 0 else 250)
    upfront_mgmt = ts.get("ts_upfront_mgmt_fee",
                           round(model.upfront_mgmt_fee / 1_000_000) if model.upfront_mgmt_fee > 0 else 0)
    upfront_timeback = ts.get("ts_upfront_timeback_fee",
                               round(model.upfront_timeback_fee / 1_000_000) if model.upfront_timeback_fee > 0 else 0)
    upfront_total = ts.get("ts_upfront_ip_fee",
                            round(model.upfront_ip_fee / 1_000_000) if model.upfront_ip_fee > 1_000_000 else model.upfront_ip_fee)

    # IP costs for development items (AlphaCore + App R&D + LifeSkills R&D)
    ip_development_total = upfront_alphacore + upfront_app_rd + upfront_lifeskills
    # Fee prepays (management + timeback)
    fee_prepays_total = upfront_mgmt + upfront_timeback

    mgmt_pct = int(ts.get("ts_management_fee_pct", round(model.management_fee_pct * 100)))
    timeback_pct = int(ts.get("ts_timeback_license_pct", round(model.timeback_license_pct * 100)))

    # Ongoing costs
    per_student_mgmt = round(per_student * mgmt_pct / 100)
    per_student_timeback = round(per_student * timeback_pct / 100)

    # Annual revenue at scale
    annual_revenue_at_scale = y5_students * per_student
    # Funding gap (incremental above current public spend ~$15k baseline)
    current_public_spend = min(15_000, per_student * 0.6)
    funding_gap_per_student = per_student - current_public_spend
    funding_gap_annual_100k = round(100_000 * funding_gap_per_student / 1_000_000_000, 1)

    # Launch/marketing capital
    launch_capital_annual = ts.get("ts_launch_capital", 25)

    # Cumulative students for IP amortization
    cumulative_students = 0
    if model.pnl_projection:
        cumulative_students = sum(p.students for p in model.pnl_projection)
    ip_amort_per_student = round(ip_development_total * 1_000_000 / max(1, cumulative_students)) if cumulative_students else 0

    # Scaling plan
    scaling_plan = []
    if strategy.phased_rollout:
        for ph in strategy.phased_rollout[:5]:
            scaling_plan.append({
                "phase": ph.phase or "",
                "timeline": ph.timeline or "",
                "students": ph.student_count or 0,
            })
    elif model.pnl_projection:
        # Build from P&L projection
        for p in model.pnl_projection:
            scaling_plan.append({
                "phase": f"Year {p.year}",
                "timeline": f"SY{26 + p.year - 1}-{27 + p.year - 1}",
                "students": p.students,
            })

    return {
        "per_student": per_student,
        "y5_students": y5_students,
        "num_schools": num_schools,
        "upfront_alphacore": upfront_alphacore,
        "upfront_app_rd": upfront_app_rd,
        "upfront_lifeskills": upfront_lifeskills,
        "upfront_mgmt": upfront_mgmt,
        "upfront_timeback": upfront_timeback,
        "upfront_total": upfront_total,
        "ip_development_total": ip_development_total,
        "fee_prepays_total": fee_prepays_total,
        "mgmt_pct": mgmt_pct,
        "timeback_pct": timeback_pct,
        "per_student_mgmt": per_student_mgmt,
        "per_student_timeback": per_student_timeback,
        "annual_revenue_at_scale": annual_revenue_at_scale,
        "funding_gap_annual_100k": funding_gap_annual_100k,
        "launch_capital_annual": launch_capital_annual,
        "ip_amort_per_student": ip_amort_per_student,
        "cumulative_students": cumulative_students,
        "scaling_plan": scaling_plan,
        "pnl": model.pnl_projection or [],
    }


# ---------------------------------------------------------------------------
# Document Section Builders (Part 1: Proposal Narrative)
# ---------------------------------------------------------------------------

def _add_confidential_header(doc: DocxDocument, target: str, cv: CountryVariables) -> None:
    """Add the confidential header line matching the benchmark."""
    p = doc.add_paragraph()
    run = p.add_run(
        f'CONFIDENTIAL \u2013 Alpha Holdings - {target} Strategic Partnership '
        f'(\u201c{cv.jv_program_name}\u201d) - {datetime.now().strftime("%m.%d.%Y")}'
    )
    run.font.size = DocxPt(10)
    run.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)


def _add_overview_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict
) -> None:
    """Build the Overview section (benchmark pages 1-2)."""
    doc.add_heading("Overview", level=1)

    # P1: Universal boilerplate
    _add_body(doc,
        "The AI world that is coming requires us to reinvent the educational system "
        "if we want to prepare our children & society to thrive. Alpha is the only one "
        "in the world building a national scale system that will transform every aspect "
        "of a student\u2019s educational journey from the ground up, including the student "
        "day, the teachers, the curriculum, and all of the technology."
    )

    # P2: Country-specific credential phrase
    _add_body(doc,
        f"The same way that Alpha has become known as the \u201cStanford of K-12\u201d, "
        f"via our partnership, we are dedicated to making \u201c{cv.credential_phrase}\u201d "
        f"the most valuable credential for the next generation of global leaders."
    )

    # P3: Partnership description with financials
    upfront_b = fin["upfront_total"] / 1000 if fin["upfront_total"] >= 1000 else fin["upfront_total"]
    scale_word = "multi-billion-dollar" if upfront_b >= 1 else f"${fin['upfront_total']:,.0f}M"
    _add_body(doc,
        f"{cv.jv_program_name} is a {scale_word} partnership between {target} and "
        f"Alpha Holdings to build the world\u2019s first AI-native K\u201312 system at "
        f"national scale. Our promise is clear and proven: students will love school, "
        f"learn 2x faster, and develop life skills for the AI age."
    )

    # P4: Cultural program introduction
    _add_body(doc,
        f"Together we will design {cv.cultural_program_name}, the life-skills engine "
        f"that ensures every {cv.country_adjective} student loves school and thrives in "
        f"the AI age. {cv.cultural_program_name} is intended to be {target}\u2019s most "
        f"valuable education asset, designed as {target}\u2019s equivalent to AlphaCore."
    )

    # P5: Architecture description
    _add_body(doc,
        f"The {cv.jv_program_name} architecture is implemented through a national "
        f"network of privately-operated, government-funded schools on the Alpha education "
        f"system, with Alpha as exclusive initial operating partner. These schools operate "
        f"within the {cv.regulatory_framework}, ensuring full regulatory compliance while "
        f"delivering transformational outcomes."
    )

    # P6: Immediacy
    _add_body(doc,
        f"{cv.jv_program_name} launches immediately. Superior outcomes create unstoppable "
        f"parent demand, and {target} inherits a proven model for national transformation."
    )

    # P7: Educational sovereignty
    _add_body(doc,
        f"By building {cv.jv_program_name} on top of Alpha\u2019s complete infrastructure, "
        f"{target} gains control of its educational sovereignty in the AI era and establishes "
        f"the global standard. {cv.jv_program_name} is operated by Alpha Holdings, the most "
        f"experienced education company in the world."
    )

    # P8: Country-specific overview
    if cv.country_specific_overview:
        _add_body(doc, cv.country_specific_overview)


def _add_transformation_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict
) -> None:
    """Build the Transformation Steps section (benchmark pages 2-3)."""
    doc.add_heading(
        "Transformation Steps and Alpha\u2019s Proven Capabilities", level=1
    )

    # Intro paragraphs
    _add_body(doc,
        "Education transformation starts with three core truths: (i) kids should love "
        "school more than going on vacation, (ii) kids can crush academics in 2 hours "
        "per day and (iii) the key to your child\u2019s happiness, character, grit, and "
        "life success are the non-academic skills they learn outside the classroom."
    )

    _add_body(doc,
        "Timeback, the AI and learning-science platform, compresses academic work into "
        "efficient mastery-based sessions tailored to each student, and gives each the "
        "rest of their day back. That time is then invested in project-based life skills "
        "\u2013 STEM, sports, arts, leadership, teamwork \u2013 that build character and "
        "capability."
    )

    _add_body(doc,
        "Alpha brings a complete, already-operating capability stack that "
        f"{cv.jv_program_name} can license and adapt rather than inventing from scratch."
    )

    # Capability bullet points (bold prefix)
    capabilities = [
        ("Reinvented school day: ",
         "from 6 hours of classes to 2 hours of academic mastery and 4 hours of "
         "project-based life skills development."),
        ("Timeback: ",
         "the AI and learning-science platform that delivers academic mastery 10x faster "
         "than conventional classrooms."),
        ("AlphaCore: ",
         "an AI-age life-skills curriculum that structures how students practice leadership, "
         "teamwork, communication, resilience, and other non-academic capabilities that matter "
         "in adult life. Alpha students love school, with a +93 NPS, and are accelerating "
         "academically by 2x in standardised tests."),
        ("Guides: ",
         "complete redefinition of the teachers\u2019 role, as a guide, coach, and mentor"),
        ("Guide School: ",
         "the talent academy for training guides that mentor and motivate students while "
         "holding them to high standards."),
        ("Incept eduLLM: ",
         "the base learning-science large language model from Incept Labs, is the only LLM "
         "that has been specifically trained with Alpha\u2019s learning science, and is able "
         "to create an unending stream of personalised content for every student using Timeback."),
        ("Marketing: ",
         "A parent education and marketing engine, built on the belief that transformation "
         "fails if parents do not understand and demand the outcomes available for their children."),
    ]
    for bold_prefix, rest in capabilities:
        _add_list_item_bold_prefix(doc, bold_prefix, rest)

    _add_body(doc,
        "Alpha has deployed this stack across multiple physical school models, including "
        "Sports academies, gt.school for gifted and talented students, wilderness training "
        "school, and eSports. Across these formats, the core academic + life-skills structure "
        "delivers consistent, measurable results."
    )

    budget = fin["per_student"]
    budget_k = f"${budget / 1000:.0f}k" if budget >= 1000 else f"${budget:,.0f}"
    _add_body(doc,
        f"Illustrative \u201ccost to educate\u201d for {cv.jv_program_name} school vs. "
        f"traditional school at {budget_k} annual budget highlights the extreme leverage of "
        f"a Timeback-based school (presented on a per-student basis, traditional budget "
        f"estimate based on industry benchmarks):"
    )

    # Cost comparison table
    _add_cost_comparison_table(doc, fin)

    _add_body(doc,
        f"This complete infrastructure is what {cv.jv_program_name} licenses, adapts, "
        f"and embeds into a {cv.country_adjective}-owned system."
    )


def _add_cultural_program_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict
) -> None:
    """Build the Cultural Program and Education Assets section."""
    doc.add_heading(
        f"The Newly Created {cv.cultural_program_name} Program and "
        f"{target} Education Assets",
        level=1,
    )

    _add_body(doc,
        "A country\u2019s most valuable educational asset is its K\u201312 life-skills "
        "program; whoever designs it is effectively writing the operating system for the "
        "next generation of leaders."
    )

    _add_body(doc,
        f"Through {cv.jv_program_name}, we will create {cv.cultural_program_name}, the "
        f"{cv.country_adjective} parallel to AlphaCore: the core national identity and "
        f"life-skills program to transform every {cv.country_adjective} student\u2019s "
        f"childhood. {cv.cultural_program_name} is intended to be {target}\u2019s most "
        f"powerful education asset, fully under {cv.country_adjective} control."
    )

    _add_body(doc,
        f"Within {cv.jv_program_name}, the {cv.country_adjective} layer sits on top of "
        f"Alpha\u2019s global technology and IP stack and is owned in {target}. The key "
        f"components of this {cv.country_adjective} layer are:"
    )

    # Cultural program bullet points
    _add_list_item_bold_prefix(doc,
        f"{cv.cultural_program_name} design: ",
        f"We start from the AlphaCore base and co-create {cv.cultural_program_name}, the "
        f"{cv.country_adjective} life-skills system just as powerful and fully under "
        f"{cv.country_adjective} control to encode {cv.cultural_values}."
    )

    _add_list_item_bold_prefix(doc,
        f"{target}-specific EdTech applications ",
        f"that integrate into Timeback, including {cv.language_subjects}."
    )

    _add_list_item_bold_prefix(doc,
        f"A specialized {target} eduLLM configuration, ",
        f"trained on {cv.edu_llm_training}, built on top of Incept\u2019s base eduLLM."
    )

    _add_body(doc,
        f"The base eduLLM from Incept Labs provides the learning-science engine and the "
        f"ability to generate an unending stream of personalised content for every student "
        f"using Timeback. The {target}-specialised eduLLM ensures all content is culturally "
        f"and linguistically appropriate."
    )

    _add_body(doc,
        f"With {cv.cultural_program_name}, {target} apps, and the {target}-specialised "
        f"eduLLM layered on top, {target} gains true educational sovereignty over what "
        f"students learn and what information is put into their heads."
    )


def _add_school_network_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    strategy: Strategy,
) -> None:
    """Build the School Network section."""
    doc.add_heading(f"{cv.jv_program_name} School Network", level=1)

    _add_body(doc,
        f"{cv.jv_program_name} is a {target}-owned national education platform "
        f"(structure TBD), with Alpha Holdings as the exclusive operating partner under a "
        f"long-term management and IP license agreement. {cv.jv_program_name} licenses the "
        f"global technology stack (Timeback, AlphaCore, Guide School, eduLLM) and adapts it "
        f"with the {cv.country_adjective} cultural layer."
    )

    _add_body(doc,
        f"{cv.jv_program_name} and Alpha will jointly design and open a family of "
        f"{cv.jv_program_name} school formats across the country designed to be accessible "
        f"to all {cv.country_adjective} students. Every {cv.jv_program_name} school runs "
        f"on Alpha\u2019s Timeback with {cv.cultural_program_name}, delivering the three "
        f"student commitments."
    )

    _add_body(doc,
        f"{cv.jv_program_name} will invest in school development and launch activities, "
        f"including national consumer marketing and enrollment infrastructure, so that each "
        f"new school type opens with strong parent demand. {cv.school_infrastructure_note}"
    )

    budget_k = f"${fin['per_student'] / 1000:,.0f},000" if fin["per_student"] >= 1000 else f"${fin['per_student']:,.0f}"
    _add_body(doc,
        f"{cv.jv_program_name} schools target a ${fin['per_student']:,.0f} per student "
        f"annual budget, with an indicative annual budget of "
        f"${fin['annual_revenue_at_scale'] / 1_000_000_000:.1f}B+ at scale."
    )

    _add_body(doc,
        f"{cv.jv_program_name} is designed to launch immediately once the framework is "
        f"agreed. Superior outcomes create parent demand and a strong political tailwind "
        f"for adoption."
    )

    y5 = fin["y5_students"]
    broader_market = int(y5 * 1.5)
    _add_body(doc,
        f"A staged scaling plan targets {y5:,} {cv.country_adjective} students by "
        f"Year 5, with a broader market opportunity of {broader_market:,}+ students:"
    )

    # Scaling plan bullets
    if fin["scaling_plan"]:
        for sp in fin["scaling_plan"]:
            students_text = f"{sp['students']:,} students" if sp["students"] else "TBD"
            _add_list_item(doc, f"{sp['timeline']}: {students_text}")
    elif fin["pnl"]:
        for p in fin["pnl"]:
            _add_list_item(doc,
                f"Year {p.year}: {p.students:,} students across {p.schools} schools"
            )


def _add_future_opportunities_section(
    doc: DocxDocument, target: str, cv: CountryVariables
) -> None:
    """Build the Future Opportunities section."""
    doc.add_heading("Future Alpha and Regional Opportunities", level=1)

    _add_body(doc,
        f"Alpha-branded private schools in {target}, regional expansion, and private-pay "
        f"offerings are intentionally treated as follow-on opportunities. They can be "
        f"structured as separate arrangements and are not required for "
        f"{cv.jv_program_name} to succeed."
    )


def _add_sequencing_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    strategy: Strategy,
) -> None:
    """Build the High-level Sequencing Plan section (matching UAE benchmark)."""
    doc.add_heading("High-level Sequencing Plan", level=1)

    # Extract student counts from strategy or P&L for phase descriptions
    phase1_students = fin["y5_students"] // 20   # ~5% of target
    phase2_mid = fin["y5_students"] // 4         # ~25% of target
    phase2_high = fin["y5_students"] // 2        # ~50% of target

    # Determine launch school year based on current date
    launch_sy_start = 26  # SY26-27 as baseline
    launch_sy = f"SY{launch_sy_start}-{launch_sy_start + 1}"

    # Always use the detailed template — matches UAE benchmark format
    phases = [
        (f"Phase 0 (Months 1-12): ",
         f"IP Transfer, {cv.cultural_program_name} design, and eduLLM model training."),
        (f"Phase 1 (Months 9-18): ",
         f"Launch of 1-2 {cv.jv_program_name} schools in {cv.first_launch_city} in "
         f"{launch_sy} under {cv.regulatory_framework} by taking over existing Model Schools."),
        (f"Phase 2 (Months 12-36): ",
         f"National rollout of the {cv.jv_program_name} school network to "
         f"{phase1_students:,}, then {phase2_mid:,}, then {phase2_high:,}+ students."),
        (f"Phase 3 (Year 3+): ",
         f"Continued scaling, with optional follow-on regional and private-pay "
         f"expatriate expansions."),
    ]

    for bold_part, rest in phases:
        _add_list_item_bold_prefix(doc, bold_part, rest)


def _add_funding_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict
) -> None:
    """Build the Funding, Investment, and Real Estate section."""
    doc.add_heading("Funding, Investment, and Real Estate", level=1)

    _add_body(doc,
        "We are flexible on structure and will work to adapt the commercial framework "
        f"to align with {target}\u2019s preferred ownership, governance, and funding model."
    )

    ip_total_m = fin["ip_development_total"]
    _add_body(doc,
        f"{cv.jv_program_name} will require ${ip_total_m:,.0f} million of capital to fund "
        f"construction of the national {cv.jv_program_name} education asset in collaboration "
        f"with Alpha Holdings. Ownership of all resulting {target}-specific IP will reside "
        f"with {cv.jv_program_name}, and the breakdown is as follows:"
    )

    # Funding breakdown bullets
    _add_list_item(doc,
        f"${fin['upfront_alphacore']:,.0f} million to license existing AlphaCore "
        f"life-skills and intangible school IP for use in {target}."
    )
    _add_list_item(doc,
        f"${fin['upfront_lifeskills']:,.0f} million to co-design and build "
        f"{cv.cultural_program_name} and the initial {cv.jv_program_name} school model."
    )
    _add_list_item(doc,
        f"${fin['upfront_app_rd']:,.0f} million of R&D capital for building "
        f"{target}-specific EdTech applications on Timeback ({cv.language_subjects})."
    )

    _add_body(doc,
        f"There is a simple, scalable commercial structure between Alpha Holdings "
        f"and {cv.jv_program_name}."
    )

    # Fee structure bullets
    mgmt_min = max(2_500, fin["per_student_mgmt"])
    timeback_min = max(5_000, fin["per_student_timeback"])
    per_student = fin["per_student"]
    y5 = fin["y5_students"]

    _add_list_item_bold_prefix(doc, "Management fee: ",
        f"{fin['mgmt_pct']} percent of revenue (or operating expenses if for a public "
        f"school), with a ${mgmt_min:,.0f} per-student annual minimum (comparable to "
        f"{cv.national_credential_reference}\u2019s management structure on a per-student "
        f"equivalent basis)."
    )

    timeback_rev_100k = round(100_000 * timeback_min / 1_000_000_000, 1)
    _add_list_item_bold_prefix(doc, "Timeback fee: ",
        f"{fin['timeback_pct']} percent of revenue or budget, with a ${timeback_min:,.0f} "
        f"per-student annual minimum (same pricing as for existing Alpha schools globally). "
        f"For each 100,000 students at ${per_student:,.0f} tuition, this equates to "
        f"${timeback_rev_100k}B annual software licensing revenue."
    )

    _add_list_item(doc,
        f"Alpha Holdings will receive up-front payments covering the first "
        f"{min(100_000, y5):,} student-years, via pre-paid management and Timeback fees "
        f"(total ${fin['fee_prepays_total']:,.0f}M)."
    )

    _add_body(doc,
        f"Initial capitalization and fee prepayments amount to roughly "
        f"${fin['upfront_total']:,.0f}M in upfront capital requirements for "
        f"{cv.jv_program_name}."
    )

    _add_body(doc,
        "To ensure schools open at quality and scale rather than as small pilots, "
        "the framework includes launch funding, scholarships, and guarantees. This "
        "scholarship and guarantee structure de-risks enrollment for the initial years."
    )

    _add_list_item(doc,
        f"{cv.jv_program_name} provides school launch activities, including parent "
        f"education, marketing, and enrollment and guide recruiting infrastructure, "
        f"expected to be on the order of ${fin['launch_capital_annual']:,.0f} million "
        f"per year during the initial launch phase."
    )

    _add_list_item(doc, cv.funding_mechanism)

    _add_list_item(doc,
        "School funding will be allocated across schools as they open, creating a "
        "stable demand base from day one and enabling each campus to open at full quality."
    )

    _add_list_item(doc, cv.school_infrastructure_note)


# ---------------------------------------------------------------------------
# Document Section Builders (Part 2: Deal Terms)
# ---------------------------------------------------------------------------


def _add_deal_terms_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    model: FinancialModel,
) -> None:
    """Build the Ed71 Schools section with deal terms table at the end."""
    doc.add_heading(f"1. {cv.jv_program_name} Schools", level=1)

    _add_list_item(doc,
        f"100% {target} owned, Alpha Holdings exclusive operator."
    )
    _add_list_item(doc,
        f"We are assuming some combination of government funding and/or a scholarship "
        f"fund will fully fund for {cv.country_adjective} students."
    )
    _add_list_item(doc,
        f"Expected ${fin['per_student']:,.0f} {cv.jv_program_name} per student annual budget:"
    )

    base_students = min(100_000, fin["y5_students"])
    target_students = fin["y5_students"]
    base_rev = base_students * fin["per_student"]
    target_rev = target_students * fin["per_student"]
    _add_list_item(doc,
        f"Base scale: {base_students:,} students x ${fin['per_student']:,.0f} budget "
        f"= ${base_rev / 1_000_000_000:.1f}B annual budget"
    )
    _add_list_item(doc,
        f"Target scale: {target_students:,} students x ${fin['per_student']:,.0f} budget "
        f"= ${target_rev / 1_000_000_000:.1f}B annual revenue"
    )
    broader = int(target_students * 1.5)
    _add_list_item(doc, f"Market opportunity: {broader:,}+ students")

    doc.add_paragraph()  # spacer

    # --- Main Deal Terms Table (placed at end of this section) ---
    _add_deal_terms_table(doc, cv, fin)


def _add_school_design_section(
    doc: DocxDocument, target: str, cv: CountryVariables, fin: dict,
    model: FinancialModel,
) -> None:
    """Build the School Design section with per-student P&L table at the end."""
    doc.add_heading("2. School Design", level=1)

    _add_list_item(doc,
        f"{cv.jv_program_name} schools will be based on Alpha education system, "
        f"delivering the three student commitments."
    )
    _add_list_item(doc,
        f"These schools are not an Alpha, and instead are based on Alpha Holdings "
        f"${50_000:,} tuition school models."
    )

    doc.add_paragraph()

    _add_body(doc, "Other expectations:")

    _add_list_item(doc,
        "Curriculum / language of instruction waivers will be in place for the first "
        "few years, similar to charter / private school requirements."
    )
    _add_list_item(doc,
        "Parents to \"opt in\" and agree to the same parent tenets (e.g. "
        "\"High Standards = Happiness\", \"Support Over Solve\", "
        "\"Privileges are Earned\", etc.) like all other Alpha Holdings schools."
    )
    _add_list_item(doc,
        "Existing school staff will be replaced by personnel trained in the Alpha "
        "education system."
    )

    doc.add_paragraph()  # spacer

    # --- Per-Student P&L Table (placed at end of School Design section) ---
    _add_per_student_pnl_table(doc, cv, fin, model)



# ---------------------------------------------------------------------------
# Table Builders
# ---------------------------------------------------------------------------

def _add_cost_comparison_table(doc: DocxDocument, fin: dict) -> None:
    """Add the cost-to-educate comparison table (Table 0 in benchmark).

    Columns: Description | Traditional School | Timeback + Teachers | Timeback + Life Skills
    """
    budget = fin["per_student"]
    # Scale from benchmark ratios
    trad_personnel = round(budget * 0.55)
    tb_teachers_personnel = round(budget * 0.10)
    tb_ls_personnel = round(budget * 0.18)
    timeback_cost = round(budget * 0.20)
    workshops = round(budget * 0.17)

    trad_total = trad_personnel
    tb_teachers_total = tb_teachers_personnel + timeback_cost
    tb_ls_total = tb_ls_personnel + timeback_cost + workshops

    headers = ["Description", f"Traditional ${budget / 1000:.0f}k School",
               "Timeback + Teachers", "Timeback + Life Skills"]
    rows = [
        ["Budget", f"${budget:,.0f}", f"${budget:,.0f}", f"${budget:,.0f}"],
        ["Personnel", f"${trad_personnel:,.0f}", f"${tb_teachers_personnel:,.0f}", f"${tb_ls_personnel:,.0f}"],
        ["Timeback / Software", "$0", f"${timeback_cost:,.0f}", f"${timeback_cost:,.0f}"],
        ["Workshops and Motivation", "$0", "$0", f"${workshops:,.0f}"],
        ["Cost to educate", f"${trad_total:,.0f}", f"${tb_teachers_total:,.0f}", f"${tb_ls_total:,.0f}"],
        ["Education Outcomes", "Current Baseline", "As Good or Better", "World Class"],
    ]

    _add_styled_table(doc, headers, rows)


def _add_deal_terms_table(doc: DocxDocument, cv: CountryVariables, fin: dict) -> None:
    """Add the main deal terms table (Table 1 in benchmark).

    Columns: Item | Up-Front Commit | Ongoing | Recipient | Notes
    """
    mgmt_pct = fin["mgmt_pct"]
    tb_pct = fin["timeback_pct"]
    mgmt_min = max(2_500, fin["per_student_mgmt"])
    tb_min = max(5_000, fin["per_student_timeback"])
    launch_annual = fin["launch_capital_annual"]

    headers = ["Item", "Up-Front Commit", "Ongoing", "Recipient", "Notes"]
    rows = [
        ["AlphaCore License",
         f"${fin['upfront_alphacore']:,.0f}M", "",
         "Alpha Holdings",
         "One-time perpetual license"],
        [f"{cv.cultural_program_name} / EdTech App R&D",
         f"${fin['upfront_app_rd']:,.0f}M", "",
         "Local expense",
         f"Estimated to be spent over 3 years. Subject to final scope."],
        [f"{cv.cultural_program_name} R&D",
         f"${fin['upfront_lifeskills']:,.0f}M", "",
         "Local expense",
         "Estimated to be spent over 3 years. Subject to final scope."],
        ["Parent Education / Launch / Guides",
         "", f"${launch_annual:,.0f}M / yr",
         "Local expense",
         "Parent education and marketing, guide recruiting and training"],
        ["Scholarships",
         "", f"${fin['funding_gap_annual_100k']}B / yr",
         "Local expense",
         "Per 100,000 scholarship students. Scale dependent."],
        # Separator row
        ["Fees below are considered in the school P&L, yielding Alpha Holdings revenue",
         "Fees below are considered in the school P&L, yielding Alpha Holdings revenue",
         "Fees below are considered in the school P&L, yielding Alpha Holdings revenue",
         "Fees below are considered in the school P&L, yielding Alpha Holdings revenue",
         "Fees below are considered in the school P&L, yielding Alpha Holdings revenue"],
        ["Management Fee",
         f"${fin['upfront_mgmt']:,.0f}M",
         f"{mgmt_pct}% budget",
         "OpEx to Alpha Holdings",
         f"{mgmt_pct}% of budget, with ${mgmt_min:,.0f} per student annual minimum"],
        ["TimeBack License Fee",
         f"${fin['upfront_timeback']:,.0f}M",
         f"{tb_pct}% budget",
         "OpEx to Alpha Holdings",
         f"{tb_pct}% of budget, with ${tb_min:,.0f} per student annual minimum"],
        [f"Total {cv.jv_program_name} Schools",
         f"${fin['upfront_total']:,.0f}M" if fin["upfront_total"] < 10_000 else f"${fin['upfront_total'] / 1000:.2f}B",
         "Scale dependent", "", ""],
    ]

    _add_styled_table(doc, headers, rows, bold_last_row=True)


def _add_per_student_pnl_table(
    doc: DocxDocument, cv: CountryVariables, fin: dict, model: FinancialModel
) -> None:
    """Add the per-student P&L comparison table (Table 2 in benchmark).

    Columns: Item | Alpha @ $50k Tuition | {JV} @ ${budget} Budget | Notes
    """
    budget = fin["per_student"]
    flagship = 50_000  # Alpha school reference

    # Alpha @ $50k ratios (from benchmark)
    alpha_guides = round(flagship * 0.28)      # $14,000
    alpha_timeback = round(flagship * 0.20)    # $10,000
    alpha_programs = round(flagship * 0.18)    # $9,000
    alpha_other_hc = 1_750
    alpha_facility = round(flagship * 0.175)   # $8,750
    alpha_misc = 1_500
    alpha_total = alpha_guides + alpha_timeback + alpha_programs + alpha_other_hc + alpha_facility + alpha_misc

    # Ed71 @ budget ratios (from benchmark)
    ed71_guides = round(budget * 0.18)         # $4,500 at $25k
    ed71_timeback = round(budget * 0.20)       # $5,000 at $25k
    ed71_programs = round(budget * 0.17)       # $4,250 at $25k
    ed71_other_hc = 1_750
    ed71_facility = round(budget * 0.12)       # $3,000 at $25k
    ed71_misc = 1_500
    ed71_mgmt = fin["per_student_mgmt"]
    ed71_ip_amort = fin["ip_amort_per_student"]
    ed71_total = ed71_guides + ed71_timeback + ed71_programs + ed71_other_hc + ed71_facility + ed71_misc + ed71_mgmt + ed71_ip_amort

    headers = [
        "Item (with per student P&L)",
        f"Alpha @ ${flagship:,.0f} Tuition",
        f"AH / {cv.jv_program_name} @ ${budget:,.0f} Budget",
        "Notes",
    ]
    rows = [
        ["Tuition", f"${flagship:,.0f}", f"${budget:,.0f}", ""],
        ["Guides", f"${alpha_guides:,.0f}", f"${ed71_guides:,.0f}",
         f"Alpha 11:1 ratio & higher comp, Other 25:1 ratio"],
        ["Timeback / Software", f"${alpha_timeback:,.0f}", f"${ed71_timeback:,.0f}",
         f"{fin['timeback_pct']}% of Budget"],
        ["Programs and Life Skills", f"${alpha_programs:,.0f}", f"${ed71_programs:,.0f}",
         "Alpha > 2x Other AH"],
        ["Other HC", f"${alpha_other_hc:,.0f}", f"${ed71_other_hc:,.0f}", "-"],
        ["Facility / CapEx", f"${alpha_facility:,.0f}", f"${ed71_facility:,.0f}",
         "Includes depreciated capex to convert locations"],
        ["Misc Expense (computer, etc.)", f"${alpha_misc:,.0f}", f"${ed71_misc:,.0f}", "-"],
        ["Management Fee", "-", f"${ed71_mgmt:,.0f}", f"{fin['mgmt_pct']}% of Budget"],
        [f"{cv.jv_program_name} IP Amortization", "",
         f"${ed71_ip_amort:,.0f}",
         f"Full amortization of IP costs over 5 year target student count"],
        ["Total Spend", f"${alpha_total:,.0f}", f"${ed71_total:,.0f}", ""],
    ]

    _add_styled_table(doc, headers, rows, bold_last_row=True)



# ---------------------------------------------------------------------------
# Table Rendering Helper
# ---------------------------------------------------------------------------

def _add_styled_table(
    doc: DocxDocument,
    headers: list[str],
    rows: list[list[str]],
    bold_last_row: bool = False,
) -> None:
    """Add a professionally styled table to the document.

    Matches the benchmark format: header row with accent background,
    alternating row shading, clean borders.
    """
    num_cols = len(headers)
    num_rows = len(rows) + 1  # +1 for header

    table = doc.add_table(rows=num_rows, cols=num_cols)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # --- Header row ---
    for ci, header_text in enumerate(headers):
        cell = table.rows[0].cells[ci]
        p = cell.paragraphs[0] if cell.paragraphs else cell.add_paragraph()
        p.paragraph_format.space_before = DocxPt(2)
        p.paragraph_format.space_after = DocxPt(2)
        run = p.add_run(header_text)
        run.bold = True
        run.font.name = "Calibri"
        run.font.size = DocxPt(9)
        run.font.color.rgb = DocxRGB(0xFF, 0xFF, 0xFF)
        # Accent background
        tc = cell._element
        tc_pr = tc.get_or_add_tcPr()
        shading_el = tc_pr.makeelement(qn("w:shd"), {
            qn("w:fill"): "006D77",
            qn("w:val"): "clear",
        })
        tc_pr.append(shading_el)

    # --- Data rows ---
    for ri, row_data in enumerate(rows):
        is_separator = (
            bool(row_data)
            and len(set(row_data)) == 1
            and len(row_data[0]) > 20
        )

        is_last = (ri == len(rows) - 1)

        if is_separator:
            # Merge all cells into one spanning separator row
            first_cell = table.rows[ri + 1].cells[0]
            last_cell = table.rows[ri + 1].cells[num_cols - 1]
            merged = first_cell.merge(last_cell)
            p = merged.paragraphs[0] if merged.paragraphs else merged.add_paragraph()
            p.paragraph_format.space_before = DocxPt(2)
            p.paragraph_format.space_after = DocxPt(2)
            run = p.add_run(row_data[0])
            run.font.name = "Calibri"
            run.font.size = DocxPt(8)
            run.font.color.rgb = DocxRGB(0x66, 0x66, 0x66)
            run.italic = True
            # Light background
            tc = merged._element
            tc_pr = tc.get_or_add_tcPr()
            shading_el = tc_pr.makeelement(qn("w:shd"), {
                qn("w:fill"): "E8E8E8",
                qn("w:val"): "clear",
            })
            tc_pr.append(shading_el)
            continue

        for ci in range(num_cols):
            cell_text = row_data[ci] if ci < len(row_data) else ""
            cell = table.rows[ri + 1].cells[ci]
            p = cell.paragraphs[0] if cell.paragraphs else cell.add_paragraph()
            p.paragraph_format.space_before = DocxPt(2)
            p.paragraph_format.space_after = DocxPt(2)

            is_bold = (bold_last_row and is_last) or cell_text.startswith("**")
            display_text = cell_text.strip("*") if cell_text.startswith("**") else cell_text
            run = p.add_run(display_text)
            run.font.name = "Calibri"
            run.font.size = DocxPt(9)
            run.font.color.rgb = DocxRGB(0x33, 0x33, 0x33)
            run.bold = is_bold

            # Alternating row shading
            if ri % 2 == 1:
                    tc = cell._element
                    tc_pr = tc.get_or_add_tcPr()
                    shading_el = tc_pr.makeelement(qn("w:shd"), {
                    qn("w:fill"): "F5F5F5",
                        qn("w:val"): "clear",
                    })
                    tc_pr.append(shading_el)

    doc.add_paragraph("")  # Spacer after table


# ---------------------------------------------------------------------------
# Paragraph / List Item Helpers
# ---------------------------------------------------------------------------

def _add_body(doc: DocxDocument, text: str) -> None:
    """Add a normal body paragraph."""
    p = doc.add_paragraph(text)
    p.style = doc.styles["Normal"]


def _add_list_item(doc: DocxDocument, text: str) -> None:
    """Add a bullet list item."""
    doc.add_paragraph(text, style="List Bullet")


def _add_list_item_bold_prefix(
    doc: DocxDocument, bold_part: str, rest: str
) -> None:
    """Add a bullet list item with a bold prefix followed by normal text.

    Matches the benchmark style: e.g. "**Timeback:** the AI platform..."
    """
    p = doc.add_paragraph(style="List Bullet")
    run_bold = p.add_run(bold_part)
    run_bold.bold = True
    run_bold.font.name = "Calibri"
    run_bold.font.size = DocxPt(11)
    p.add_run(rest)


# ---------------------------------------------------------------------------
# Summary Markdown (for frontend display)
# ---------------------------------------------------------------------------

def _build_summary_markdown(
    target: str, cv: CountryVariables, ts: dict, model: FinancialModel
) -> str:
    """Build a summary markdown string for frontend display."""
    per_student = ts.get("ts_per_student_budget", 25_000)
    y5_students = int(ts.get("ts_students_year5",
                              model.pnl_projection[-1].students if model.pnl_projection else 100_000))
    upfront = ts.get("ts_upfront_ip_fee",
                      round(model.upfront_ip_fee / 1_000_000) if model.upfront_ip_fee > 1_000_000 else model.upfront_ip_fee)

    lines = [
        f"# {cv.jv_program_name} \u2014 Combined Proposal",
        f"## 2hr Learning (Alpha) \u00d7 {target}",
        "",
        f"**Program Name:** {cv.jv_program_name}",
        f"**Cultural Program:** {cv.cultural_program_name}",
        f"**Credential:** {cv.credential_phrase}",
        "",
        "### Key Terms",
        f"- **Upfront Ask:** ${upfront:,.0f}M",
        f"- **Per-Student Budget:** ${per_student:,.0f}",
        f"- **Year 5 Students:** {y5_students:,}",
        f"- **Management Fee:** {ts.get('ts_management_fee_pct', 10)}%",
        f"- **Timeback License:** {ts.get('ts_timeback_license_pct', 20)}%",
        "",
        "### Scaling Plan",
    ]

    if model.pnl_projection:
        for p in model.pnl_projection:
            lines.append(
                f"- Year {p.year}: {p.students:,} students | {p.schools} schools | "
                f"${p.revenue:,.0f} revenue"
            )

    lines.extend([
        "",
        "*This proposal document is confidential and non-binding. "
        "All terms are subject to final negotiation and execution of definitive agreements.*",
    ])

    return "\n".join(lines)
